### ISSUE TITLE
[Not urgent] Projectile missaligned for the first 1-2 seconds when coming out of the barrel

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#10]
![obraz](https://user-images.githubusercontent.com/71346253/180613627-2b623e0c-96b2-4642-a6cb-59d617009c85.png)

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/rbasamoyai/CreateBigCannons/commit/abc2287027184a65523d94a1d12621063e141b9d. However, I did notice that when falling straight down, the projectile might "go out" of its hitbox.
