### ISSUE TITLE
cannon is stoping with working randomly

### ISSUE THREAD

**Issue by TechnicalAmazing** [Cannoneers-of-Create/CreateBigCannons#107]
- OS: macOS single player world
 - Version: latest (1.18.2)

**To Reproduce**
When you fire a cannon multiple times, on a random moment the cannon stoped working. If I rebuilt de cannon at the exact same location the cannon stil doesn't work. (and yes I loaded the cannon)

**Comment by rbasamoyai** [comment]
Footage?

**Comment by TechnicalAmazing** [comment]
do you mean video?

**Comment by rbasamoyai** [comment]
Yes, please send a video of the behavior, as well as any additional steps to reproduce.

**Comment by TechnicalAmazing** [comment]
oke i am back in a moment

**Comment by TechnicalAmazing** [comment]
sorry but the video is to big I need to make it smaller.

**Comment by TechnicalAmazing** [comment]
is it oke to send you a google drive mail. because the video is still to big.

**Comment by TechnicalAmazing** [comment]
https://drive.google.com/file/d/1ucfDP_k52cr-8LRjXFYxtblVwJ4QeJUA/view?usp=sharing 
Here is the video.

**Comment by rbasamoyai** [comment]
Can't access the video, try uploading it directly to github

**Comment by TechnicalAmazing** [comment]
That isn't possible beceuse the video size is to big. even when I set it to 720p :/ .

**Comment by rbasamoyai** [comment]
Try using a video compressor, such as 8mb

**Comment by TechnicalAmazing** [comment]
oke

**Comment by TechnicalAmazing** [comment]
sorry 8mb website that you send is a little slow I am back when it's finished.

**Comment by TechnicalAmazing** [comment]
here is the link: 
https://transcode-e8abc4.8mb.video/8mb.video-BDj-D4TuwUGD.mp4

**Comment by rbasamoyai** [comment]
Please post the video in the conversation instead of linking to a website that only temporarily hosts your video. This is why I asked you to use a compressor.

**Comment by TechnicalAmazing** [comment]
oh sorry 
This is the first time I posted a something on GitHub.

**Comment by TechnicalAmazing** [comment]
https://user-images.githubusercontent.com/103304334/200183292-3228cf9d-1ad6-4425-a3f1-3bd821b44acc.mp4

I don't know if you can see enough

**Comment by rbasamoyai** [comment]
too little powder charges to blocks travelled, you need to fix that

**Comment by TechnicalAmazing** [comment]
oh thx, but what about that it sometimes work and sometimes not?

**Comment by rbasamoyai** [comment]
Because it's a random chance, you *could* make the barrel longer than what is safe but it follows that the projectile might get stuck. Use more powder charges, and check the cannon block tooltip for the "squib ratio".

**Comment by TechnicalAmazing** [comment]
oh so sorry for disturb you.

**Comment by TechnicalAmazing** [comment]
i have 1 question what does do the squib ratio?
