### ISSUE TITLE
make it possible to make a 64 block cannon

### ISSUE THREAD

**Issue by boom312** [Cannoneers-of-Create/CreateBigCannons#108]
why is the cap for size 64 blocks but there's no way to make a cannon that can shoot with 64 block length

I don't care how costly it is to make it, if I have to add solid Nethersteel blocks to the sides of my cannon I'll do it

I beg you

let me shoot a 64 block cannon

**Comment by rbasamoyai** [comment]
It is already possible to config the maximum size of a cannon in crafting and assembly.
