### ISSUE TITLE
Sequence gearshift works strangely

### ISSUE THREAD

**Issue by SuperSpaceEye** [Cannoneers-of-Create/CreateBigCannons#109]
**Describe the bug**
A sequence gearshift when using turn angle turns by less angle than it should.

 - OS: [e.g. Windows]
 - minecraft 1.18.2. mod version: beta-0.4.1

I do also have a bunch of other mods installed.

https://user-images.githubusercontent.com/44544509/200933671-2a6fe73e-cada-4dda-8607-844a964eaf5a.mp4

**Comment by rbasamoyai** [comment]
Intentional gearing down of cannon speed, could possibly make it configurable

**Comment by SuperSpaceEye** [comment]
The slow speed doesn't help. So is it intentional?

**Comment by rbasamoyai** [comment]
yes, this was an intentional feature. see the last part of my previous comment though

**Comment by SuperSpaceEye** [comment]
Oh, ok.
