### ISSUE TITLE
wont work with flywheel

### ISSUE THREAD

**Issue by MCJEModder2026** [Cannoneers-of-Create/CreateBigCannons#118]
**Describe the issue**
this mod does not work with latest flywheel

 - OS: macos 13
 - CreateBigCannons Version: 1.18.2-beta-0.4.1
 - Other Mods: N/A

**To Reproduce**
1. install latest flywheel
2. launch mc with createbigcannons and flywheel
3. crash

**Expected behavior**
the minecraft instance would launch normally

**Comment by rbasamoyai** [comment]
Don't know what you're getting at here, but if it has to do with Create updated to 0.5.0.g and Flywheel 0.6.8 that has been addressed and is in the latest nightly.

**Comment by MCJEModder2026** [comment]
> Don't know what you're getting at here, but if it has to do with Create updated to 0.5.0.g and Flywheel 0.6.8 that has been addressed and is in the latest nightly.

i cant get the latest nightly on curseforge and i need to distribute a pack with it

**Comment by LilJagty** [comment]
Hey, why was this closed? @rbasamoyai The update still hasn't been released on CurseForge

**Comment by rbasamoyai** [comment]
Check the discord server for nightlies, using `/download nightly` or `/download info`

**Comment by LilJagty** [comment]
Thanks for the response, but this isn't helpful as I'm trying to release a modpack with the latest fixes.
