### ISSUE TITLE
Sliding breech doesn't work properly near bearing attatchments that haven't been placed

### ISSUE THREAD

**Issue by Tayto671** [Cannoneers-of-Create/CreateBigCannons#124]
**Describe the bug**
The sliding breech can open but not close when near blocks on a bearing set to place only when destroyed

 - OS: [e.g. Windows]
 - Version: [e.g. nightly-4b2bde7 / beta-0.1]

**To Reproduce**
1. Place a block on a bearing set to place only when destroyed
2. Rotate the block at all so that it isn't a placed block anymore
3. Put a sliding breech near it
4. Sliding breech will open but not close

**Comment by rbasamoyai** [comment]
Intended behavior
