### ISSUE TITLE
[1.18.2] Liquified metals have minecraft:water tag

### ISSUE THREAD

**Issue by HonzaVinCZ** [Cannoneers-of-Create/CreateBigCannons#126]
**Describe the bug**
All liquified metals have minecraft:water tag which makes them usable in any machine recipe using water tag. So in other mods they can be used for brewing potions, food or making chemicals. I would like to ask you to remove that flag if possible so it does not interfere with other mods. 

 - OS: 
 Windows 11
 
 - Version:
createbigcannons-1.18.2-beta-0.4.1.jar

**To Reproduce**
Liquified metals can be found in primarly machine processing recipes where tag minecraft:water is used. (Using JEI).

**Expected behavior**
Liquified metals should not have minecraft:water tag.

**Screenshots**

![2022-12-21_15 21 18](https://user-images.githubusercontent.com/29098779/208927346-7f36d8ca-2750-472f-9060-85341be1d62b.png)

![2022-12-21_15 21 52](https://user-images.githubusercontent.com/29098779/208927355-4bc7bf9e-5fb7-4baf-a996-29946f22017f.png)

![2022-12-21_15 21 57](https://user-images.githubusercontent.com/29098779/208927361-104a0e8f-6ee2-4f0a-b8ad-794e2613df64.png)

![2022-12-21_15 22 09](https://user-images.githubusercontent.com/29098779/208927371-44ee5980-c4de-4b1d-9e63-115429b62798.png)

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/rbasamoyai/CreateBigCannons/commit/501f3e76035ae2c3e2291d9c40e58c42d508e028.
