### ISSUE TITLE
not urgent shells cant be pushed by pistons

### ISSUE THREAD

**Issue by euanPC** [Cannoneers-of-Create/CreateBigCannons#13]

**Comment by euanPC** [comment]
yes powdered charges can

**Comment by euanPC** [comment]
yet powdered charges can

**Comment by rbasamoyai** [comment]
they should be pushable, try orienting the shells the right way, if not, please send footage.

**Comment by euanPC** [comment]
figured it out the shrapnel shot doesnt work

**Comment by Qastro2** [comment]
euanPC please drop me the leaked build on my discord Dio Brando#1836

**Comment by Qastro2** [comment]
euanPC please drop me the leaked build create aeronautics on my discord Dio Brando#1836
