### ISSUE TITLE
1.18.2 Cannons crashes game.

### ISSUE THREAD

**Issue by toErIpNid** [Cannoneers-of-Create/CreateBigCannons#131]
**Describe the bug**
When using big cannons with other mods, it causes the game to crash on start up. 

 - OS: Windows 10
 - MC Version: 1.18.2
 - Mod Ver: 1.18.2-beta-0.4.1.jar

**To Reproduce**
1. Install Export File.
[Crash.zip](https://github.com/rbasamoyai/CreateBigCannons/files/10309247/Crash.zip)
  
2. Profit.

**Expected behavior**
It not crashing upon start up.

**Comment by toErIpNid** [comment]
I forgot to put the crash log down, I'll do it later.

**Comment by rbasamoyai** [comment]
Closing since no log in two days
