### ISSUE TITLE
The mod doesn't work with Create 0.5g

### ISSUE THREAD

**Issue by Sshmoob** [Cannoneers-of-Create/CreateBigCannons#132]
**The Bug**
Create big cannons wants flywheel 0.6.5, and because you need flywheel 0.6.8 in order to run the newest version of create, you can't use the newest version of create (0.5g) with the mod.

 - Version: 1.18.2-beta-0.4.1

**To Reproduce**
1. Install forge for 1.18.2 (I used 40.1.92, the latest at the time of writing)
2. Get the latest version of Create and Flywheel (Create 0.5g, Flywheel 0.6.8)
3. Install the newest version of Create Big Cannons (beta 0.4.1)
4. Launch the game
5. The game crashes because a newer version of flywheel than what Create Big Cannons wants is installed.
**Expected behavior**
The game runs with the newest version of flywheel and therefore the newest version of the Create mod.

**Screenshots**
![image](https://user-images.githubusercontent.com/80718549/209867749-fdfef00b-9437-4d4e-9c51-bdf77f1f53f6.png)

**Notes**
It seems like you tried to future proof the mod for newer versions of flywheel, but didn't expect the Create team to bump the version by 3.

**Comment by rbasamoyai** [comment]
Fixed in latest nightly

**Comment by Xplodin** [comment]
is there going to be a curseforge push for this mod so I can use it in my modpack?

> Fixed in latest nightly

**Comment by StormDragon-64** [comment]
I went on the discord server and all he said was 'maybe in January' (I asked in December)
I have a modpack too, and now that the flywheel bugs have been fixed (flywheel 0.6.8a fixed some stuff) this is the only reason I can't update my modpack to 0.5g.

**Comment by Sshmoob** [comment]
Yeah, now it's been so long there's another Create release
