### ISSUE TITLE
create big cannons and create needs flywheel but its different versions

### ISSUE THREAD

**Issue by arbentman106** [Cannoneers-of-Create/CreateBigCannons#136]
when i try to load the mod it comes up with an error saying that create big cannons requires flywheel between 0.6.5 and 0.6.7 
but another message under it says create mod needs flywheel between 0.6.8 and 0.6.9 so i dont know how to get rid of the error

**Comment by rbasamoyai** [comment]
Fixed in latest nightly, check discord
