### ISSUE TITLE
something doesn't work when using with another mod

### ISSUE THREAD

**Issue by EnderLiam1072** [Cannoneers-of-Create/CreateBigCannons#143]
You said you fixed the issue when Create needs a specific version of Flywheel and Create Big Cannons needs a different version of flywheel, but it still doesn't work.

Do you think you could maybe take a look please?

Thank you, much appreciated.

**Comment by rbasamoyai** [comment]
The nightly versions of CBC work with the latest Create update. You can download them from this github or from the mod discord.
