### ISSUE TITLE
It should work with the latest version of flyheel.

### ISSUE THREAD

**Issue by miku1881** [Cannoneers-of-Create/CreateBigCannons#144]
I installed create big cannon, but when I run the latest version of flywheel, it tells me to lower the version and won't start.

Please make it possible to start with the latest version of flywheel!

**Comment by Kvass134** [comment]
Yes, it's very necessary. I'm building a big modpack and this is a big problem.

**Comment by rbasamoyai** [comment]
This is planned

**Comment by rbasamoyai** [comment]
Edit: re-read this again and it has already been implemented a long time ago in the indev version
