### ISSUE TITLE
Cannon components over 1 block in size can be walked through

### ISSUE THREAD

**Issue by cakeGit** [Cannoneers-of-Create/CreateBigCannons#155]
**Describe the bug**
Quite minor and more a polish, but you can walk into cannon components if you are walking diagonally,

 - OS: Windows
 - Version: All - Doing this on 1.18.2-beta-0.5.jar

**To Reproduce**
1. Go in-game
2. Place down a cannon chamber with a hitbox larger than 1 block
3. Walk into the cannon diagonally
4. Player will no-clip into the cannon

This is because Minecraft will not check blocks that are not immediately next to the player, and ignore hitboxes you are already in.
This is very annoying, but I would suggest making a hitbox where the corners are cut out like:
![image](https://user-images.githubusercontent.com/65340665/218517957-53218af8-279a-4a2d-ba56-969aafe8465d.png)

**Expected behavior**
Cannon to block moving inside

**Screenshots**

Walking into a regular block-size cannon chamber:
![image](https://user-images.githubusercontent.com/65340665/218515772-a5d07734-dff8-44b8-b7bb-296e1f267ab4.png)

Walking into a larger cannon chamber:
![image](https://user-images.githubusercontent.com/65340665/218515982-2fb982fc-3f4f-47c5-b60a-fa673f8020ae.png)

**Comment by rbasamoyai** [comment]
Shrunk the collision hitboxes to the 16 x 16 block. you will be able to walk through some of the *visual* cannon but it shouldn't be too off-putting
