### ISSUE TITLE
how to install mod with fluid shot and works with 0.5.0 patch h 

### ISSUE THREAD

**Issue by hello134267** [Cannoneers-of-Create/CreateBigCannons#159]
**Describe the issue**
A clear and concise description of what the issue is.

 - OS: [e.g. Windows]
 - CreateBigCannons Version: [e.g. nightly-4b2bde7 / beta-0.1]
 - Other Mods: [e.g. Waystones 1.18.2-10.1.0]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by rbasamoyai** [comment]
Unclear what is being asked here, closing
