### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by ghost** [Cannoneers-of-Create/CreateBigCannons#16]
- OS: Windows11 22H2
 - Version: 0.1-beta
Forge vision 40.1.68

server args
-Xms4G -Xmx8G -server -XX:+IgnoreUnrecognizedVMOptions -XX:-UseG1GC -XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true  -XX:+UseCompressedOops -XX:+OptoScheduling -XX:+OptoBundling -XX:+UseStringDeduplication -XX:+AllowParallelDefineClass -XX:+UseVectorCmov -XX:-DontCompileHugeMethods -Dfile.encoding=UTF-8

Log:
[debug.log](https://github.com/rbasamoyai/CreateBigCannons/files/9180285/debug.log)
[latest.log](https://github.com/rbasamoyai/CreateBigCannons/files/9180287/latest.log)

**Comment by rbasamoyai** [comment]
I'm not sure if Flywheel is needed or not on the serverside, if not I'll get a quick fix in.

**Comment by ghost** [comment]
> I'm not sure if Flywheel is needed or not on the serverside, if not I'll get a quick fix in.

Flywheel is render stuff, not need on server side

**Comment by rbasamoyai** [comment]
right then, i'll just add an `@OnlyIn(Dist.CLIENT)` (🤮), it's a dirty solution but it should work.

**Comment by rbasamoyai** [comment]
Should be fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/868b50d93f6c8cb9a2bc2a198411b334d2997932.

**Comment by rbasamoyai** [comment]
Actually, I'll get this tested, and then I'll actually close the issue if it does actually work, just hang tight

**Comment by rbasamoyai** [comment]
Yep, doesn't seem to crash on server start 👍
