### ISSUE TITLE
[UX&Balance] Add Proper Shells to Big Cannons

### ISSUE THREAD

**Issue by minMaximilian** [Cannoneers-of-Create/CreateBigCannons#161]
# UX & Balance Suggestion
## Background
After running PvP tests on our server we've determined a few fatal flaws within the BigCannons mod that makes it hard to approach, survival unfriendly, cumbersome and potentially limiting creativity.

These changes are suggestion in anticipation of create aeronautics, dealing mostly with spatial challenges when building a big cannon that will prove to be detrimental when making airships, tanks, battleships and different sorts of turrets when defending your base. 

## Spatial Difficulties
Concurrently Big Cannons take quite a lot of space to setup with the most simplest method. See picture below (Examples not fully functional it's the concept that mat
![HugeUncomplicatedButCumbersome](https://user-images.githubuserconte

During our trials we found that players familiar with create had some issues setting this loading mechanism up. Issues stemmed from the following.
- Blocks aren't placed directionally making it so you have to rotate the charges in correct direction. Making it unintuitive
- Timing the circuit so it loads properly
- Certain manual systems with timing, loading, closing the breach and firing the circuit. Were deemed to be cumbersome and caused to failures and cannon misreloads. This issue was even annoying to deal with in creative.
- Creating pretty contraptions that can handle these turrets with the complex loading mechanisms is troublesome to even some of our most astute builders in our server.
- Long loading rods creating building complication

There are solutions to these problems such as smarter engineering. Such as a radial chassis with powder charges to reduce the amount of rods needed to load the cannon. Case and Point the example below.

![CompactButComplicated](https://user-images.githubusercontent.com/53843385/222807526-64f5f34a-2160-495a-948b-be466759a025.png)
nt.com/53843385/222807479-c34cafd2-8323-4df1-bebc-57b0e0375d60.png)
ters)

This is a great way to increase the creativity by encouraging engineering to supersede these problems. Where we can sacrifice width in multiple dimensions such as width and height to shorten our rod needed to load this.

But this increase in engineering creativity sacrifices creativity in other ways we will see later.

## First Example,
We previously used a ship gun to demonstrate our previous points. The ship gun in question is at a much larger 1.5:1 scale then the real life counterpart. Which is a reasonable scale for minecraft. After sacraficing space horizontally to put in the better loading mechanism making a ship gun becomes near impossible as each gun has trouble being fitted in a battery.

![CantFitComplicatedMechanismSideBySideShipBatteriesImpossible](https://user-images.githubusercontent.com/53843385/222807571-37af4850-447a-4ae5-b337-f9430abbf45f.png)

## Example Two,
Larger loading mechanism will be trouble for vehicles smaller proportion, in the new create simulated mod.

For example tanks, in the following picture.

![MinimumTankTurretCrossSection](https://user-images.githubusercontent.com/53843385/222807628-b81d0deb-d3d3-485f-a80d-b3ee37b58fc2.png)

The loading mechanism outgrows the turret and turret is very big thanks to this. Making it hard to design nicer small tank builds. Making it so a tank needs to have an autocannon which isn't desireable.

Another undesirable thing is how little charge we can put into this cannon, making the projectile, slow, hard to aim, and potentially just straight up useless for engagement.

Hence small big cannons aren't useful

# Solution
## Background
We have a solution and it's very simple and it still makes sense within the confines of the mod, especially since we have autocannons. Is to add modern shells just how they were invented in 1850s. It doesn't make much sense to not have those when we have autocannons with the same said shells.

## An Interesting Implementation
First we need to craft a block out of brass for the cartridge we are gonna make. In this picture here is a potential cost effective recipe for an unhallowed empty brass shell.

![EmptyShellRecipe](https://user-images.githubusercontent.com/53843385/222807710-20f34763-6df9-4c42-85bf-81cd5734e85c.png)

We would then need to use the excellent and cool mechanic of boring these shells, I've barrowed just the normal JEI to show this. process.

![BoreShells](https://user-images.githubusercontent.com/53843385/222807750-6fe30fad-0a1c-430f-9dbe-47e46721ebfb.png)

These would then get deposited in a conveyer in your shell factory, and nothing looks cooler then a bunch of shells/ammo rolling through conveyer belts ready to be processed. Until they get to the next stage. Which is loading the empty shells with the payload.

Here we will use recipe sequences to craft customizable shells. 

![ShellCrafting](https://user-images.githubusercontent.com/53843385/222807791-32371a44-6ce1-40b8-bba7-5044ba81b9f4.png)

This recipe would be repeatable and only endable by adding the warhead/charge. Creating a complete shell. In this example we have two gunpowder and Armour Piercing head but we could've just as easily added another gunpowder prior to this to give the gun more velocity. 

This will also simplify fluid shots by just adding a spout to the process. As of right now they are extremely cumbersome to use and no one in our server is imagining themselves using it.

This will help reduce our loading mechanisms down to two-four blocks maximum.

For example in this picture we have now a shell in our tank turret that can actually fit much more nicely. 

![ShellIdea](https://user-images.githubusercontent.com/53843385/222807834-c50f2e57-9e21-49e8-ba0a-d27313890b36.png)

Now all we need is to just load the shell which contains the exact same stats as it did from the less compact version.

We can now also fit three cannons reasonably in the larger ship gun. Or fit a turret on a train reasonably.

# Addendum Reasoning
## Spatial Requirements
With airships wether through valkyrien skies or aeronautics, builds will get a lot more complex with more parts having to be intermingled with big cannons. Reducing the spatial stress on loading a cannon will allow for more functional and more aesthetical turrets, and cannons.

## Moving Shell Production from the Cannon area to the Factory makes more sense
Moving shell production from the cannon to the factory makes more sense. It's how we do it in real life, and create is also mostly a mod focused on automation and the factory line. Relocating this simple bit of production the factory line gives boring mechanics more life rather then just a single use.

## Reduced Mental Overhead and new gameplay potential
Shells are simple, another mechanic we can have with shells is manual loading where we can just right click the shell into the breach. Which would allow multicrew tanks with a driver and a gunner to be encouraged. Multicrew also means in the long run reduced overhead of controlling these contraptions.

## Possible Extra Suggestions
Shells should be transported by mass cargo e.g. Train and conveyer.
They should give slowness to the player while carrying them. 
Just how we have in the picture above we can also simplify the loading mechanic just to a piston. 

## It's more survival friendly
Reducing space constraints allows for better balance between the fact minecraft is a survival game with resources and not everyone can afford to pack on hundreds of layers of iron on the turret. Reduced surface size reduces the amount of extra armour/resources you will need to put on these big cannons.

## Potential for better cannon mechanics
Reducing the warheads down to shells may allow for a different way of balancing cannon materials. Reducing the amount of cannon chambers and making it so velocity is purely dependent on the quality of the material preventing catastrophic failure.

## High Stress
Combat is a high stress situation and a simplification would be much appreciated when it comes to loading shells.

**Comment by rbasamoyai** [comment]
Certain ideas from this issue have been incorporated or reworked into recent updates. I think this can be closed for now
