### ISSUE TITLE
make cannons turnable by the mechanical bearings

### ISSUE THREAD

**Issue by RGBRedGreenBlue** [Cannoneers-of-Create/CreateBigCannons#163]
Could it be possible to please make built cannons turnable by the Mechanical Bearings?

I mostly want this for having multiple big cannons and autocannons be able to turn together properly, instead of turning individually and then clipping through eachother, but when they are made into contraptions the cannon mounts cannot be moved.

![2023-03-13_19 30 07](https://user-images.githubusercontent.com/105780563/224654254-89bd032a-c9e5-4f1c-8867-5bbe8cb173fb.png)
So that they don't do this

If you could please change this I, and probably others, would greatly appreciate it, Thanks.

**Comment by rbasamoyai** [comment]
Not quite possible due to how base create works
