### ISSUE TITLE
Particles and perhaps projectiles tp ladder like at high angles

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#17]
- OS: [e.g. Windows]
 - Version: [beta-0.2]

**To Reproduce**
1.Fire the cannon at a high angle, the cannon was 7 chambers long, facing west

**Expected behavior**
Normal trajectory

**Screenshots**
![obraz](https://user-images.githubusercontent.com/71346253/181072724-dbb6addf-f0b0-488e-a799-3ac08878b937.png)

**Comment by rbasamoyai** [comment]
Bit of a late reply and I've somewhat addressed this in the discord, but I may be stretching the limits of what MC is supposed to handle with high velocities.

If possible, I could make a non-entity based projectile system that would track and handle high velocity projectiles better than MC, although that would very much be non-urgent and on the backburner for now.

**Comment by Abrams11IsBack** [comment]
yeah, non-entity based system will be much appreciated due to mc entities being really not made for stuff like this

**Comment by rbasamoyai** [comment]
Currently remedied in https://github.com/rbasamoyai/CreateBigCannons/commit/fa8c88300ebcd4e5a7083ad39be5012799f69199 by increasing update interval from every 20 ticks to every tick.

I do not consider this a permanent solution but if it happens that it is suitable for the velocity range in this mod I may consider closing this as resolved.
