### ISSUE TITLE
Unbored cannon parts can be drilled through their side

### ISSUE THREAD

**Issue by saltyseadoggo** [Cannoneers-of-Create/CreateBigCannons#172]
As per the screenshot below, the cannon drill doesn't actually care if an unbored cannon part is facing the right way, and will drill the cannon part through its side. One would expect the cannon drill to check if the cannon part's end is facing towards the drill bit and refuse to drill if it isn't.

![2023-04-10_20 34 07](https://user-images.githubusercontent.com/69029346/231049501-91b668dc-2687-4ee0-b2f6-1568dfd3543d.png)

**Comment by rbasamoyai** [comment]
I think I've actually encountered this before - mostly thought no-one would really notice. However, this could probably be solved with a direction check or something like that. I'll take care of it later

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/e2be52c4701f34226c21c5ae7154b66bf067ebdb
