### ISSUE TITLE
When adding new boring recipes, borable block in JEI doesn't face the right way

### ISSUE THREAD

**Issue by saltyseadoggo** [Cannoneers-of-Create/CreateBigCannons#173]
I tried to add a boring recipe to turn an oak log into Twilight Forest's hollow oak log. I've found, however, that JEI does not show the log facing the right way, with the end facing the drill bit. I couldn't find a tag or the like to make the log face the right way. Is it possible to do this? If not, I'd like to request that blocks with an `axis` blockstate, like the unbored cannon blocks and logs, be automatically made to face with their end to the drill bit if they are used in custom boring recipes.

![2023-04-10_20 47 54](https://user-images.githubusercontent.com/69029346/231051336-fb5c5373-13dd-4e71-9d0a-cfda54eceff1.png)

**Comment by saltyseadoggo** [comment]
Correcting myself: the unbored cannon blocks have `facing` blockstates, not `axis` blockstates. Still, it would be great if the boring recipe preview would recognise blocks with an `axis` blockstate and make them face the right way.~

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/caef767caa0288b41ae2158dd30d9de3f7dc4ce6

**Comment by LogicWheat** [comment]
Can you tell me how to add new boring recipes?thx!!

**Comment by LogicWheat** [comment]
@saltyseadoggo
