### ISSUE TITLE
Not compatible with REI

### ISSUE THREAD

**Issue by wellcoming** [Cannoneers-of-Create/CreateBigCannons#174]
**Minecraft Version:** 1.18.2
**Mod Version:** 1.18.2-0.5.1-nightly-561ee21
**Fabric Loader Version:** 0.14.18
**Fabric API Version:** 0.76.0
**REI Version:** 8.3.594

### Description
When using the CreateBigCannons mod with the Fabric version, the recipes are not being displayed in Roughly Enough Items (REI). This makes it difficult for players to know how to craft items in the mod.

### Steps to reproduce
1. Install the `CreateBigCannons mod` (Fabric version), `Fabric API`, `Create` and `REI`.
2. Launch Minecraft.
3. Open inventory and click on the `REI` interface.
4. Search for items from the `CreateBigCannons` that can be drilled.
5. Observe that the crafting recipes for these items are not displayed in `REI`.

### Expected behavior
When using the CreateBigCannons mod with the Fabric version, the crafting recipes for the mod's items should be displayed in REI, allowing players to easily access the information and craft the items.

### Screenshots
![image](https://user-images.githubusercontent.com/74850890/231453335-ef677996-e6ce-4d41-a83f-9a969c989034.png)
(no recipes)

**Comment by BraveCaperCat2** [comment]
very difficult??? this just means modpack developers have to use JEI instead. no big deal or anything.

**Comment by rbasamoyai** [comment]
Update on this: will not address until Create's REI integration is fixed. I'll check on it again some time later

**Comment by rbasamoyai** [comment]
Fixed by commit https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/3f1c593585054d2325e5bad3f1e3e4e57c6ab908.
