### ISSUE TITLE
Autocannon emptying shells but not firing 

### ISSUE THREAD

**Issue by Drewdaddy07** [Cannoneers-of-Create/CreateBigCannons#176]
After creating an auto cannon and mounting it, once I try to fire the empty cartridges go into my inventory but no bullet exits the cannon. I attempted to change the direction of the recoil spring, replace the cannon numerous times, and many other things to no avail.

**Comment by rbasamoyai** [comment]
Did you get autocannon cartridges from the search menu? Those cartridges are known to not function properly. If so, get your cartridges from the proper CBC tab

**Comment by Drewdaddy07** [comment]
Awesome, thanks for the quick reply and helping me!
