### ISSUE TITLE
Bag of Grapeshot does not have Trajectory Ballistics.

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#19]
* Trajectory ballistics of Bag of Grapeshot shell is missing.
* Does not damage soft blocks.
* Very small render distance (~30 blocks)
* (Edited) Bug works with both cannons.
 
- Version: **nightly-e4832d5**

1. Load cannon with Bag of Grapeshot (createbigcannons:bag_of_grapeshot)
2. Fire, and notice that Bag of Grapeshot does not have ballistics and does not damage soft blocks.

https://user-images.githubusercontent.com/109973204/181203861-db94c419-181d-4129-9cba-fb4b63e32450.mp4

https://user-images.githubusercontent.com/109973204/181203890-f0ae8637-ff65-4ff2-9162-41df6d794cd1.mp4

**Comment by rbasamoyai** [comment]
"Soft blocks" is a bit of a limited category defined by a data tag (`#createbigcannons:grapeshot_shatterable` and `#createbigcannons:shrapnel_shatterable`) so I'd love to hear what should be added.

As for grapeshot, as well as shrapnel, gravity/ballistics is currently non-existent. I'm not sure if it should be added.

Finally, for the render distance culling: - It is mostly MC's doing. I could increase the distance that it is visible, if you'd like.

**Comment by Crabanutij** [comment]
In my opinion, grapeshotes should have adjusted range or 50% less physics than solid shots (if added physics) and procents of penetrating different types of blocks, for example wool: 50%, glass and glass panes: 100%, wood: 30%. And i think shrapnel would use against entities and fragile blocks, like glass panes, glass, flower pots etc. Actually, i will add ideas in another issue.

About "Soft blocks": we can ask some help in your discord server, and then choose manually what should be tagged (#createbigcannons:grapeshot_shatterable)

For the distance culling: -You can increase the distance, like the create assembled contraptions have.
