### ISSUE TITLE
[CRASH] CBC crashes with Valkyrien Skies v2.1.0 (beta 11)

### ISSUE THREAD

**Issue by DaRealSparky** [Cannoneers-of-Create/CreateBigCannons#195]
As the title says, the mod is crashing with Valkyrien Skies v2.1.0 beta build 11.

[Crash Log Here](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11378712/crash-2023-05-02_20.10.59-fml.txt)

To Reproduce:
1: Load Minecraft 1.18.2
2: Install Forge 40.2.2
3: Install Create Big Cannons beta 0.5b (latest as of writing)
4: Install Valkyrien Skies v2.1.0 Beta 11 (latest as of writing)
5: Launch game and wait for it to finish loading

**Comment by rbasamoyai** [comment]
Please use the latest CBC update 0.5.1, it should have various compat with VS.
