### ISSUE TITLE
Ram Head and Worm Head unable to push Glue.

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#20]
When **Cannon Loader** pushes charges and shells, _glue stay in the same place_, where it was before the cannon loader pushed it.

 - Version: **nightly-e4832d5**
1. Apply glue on charges or shells.
2.  Move them with Ram Head or Worm Head.

https://user-images.githubusercontent.com/109973204/181221384-25f266a8-1844-4a20-a427-52e698ebe997.mp4

https://user-images.githubusercontent.com/109973204/181221403-612757c5-8316-41af-b0fc-fc6a09436123.mp4

**Comment by rbasamoyai** [comment]
Not exactly sure of the uses of moving glue when the cannon loader is just for loading munitions just before consumption by the cannon. Also, this could potentially mean having other items attached be moved by the glue.
