### ISSUE TITLE
autocannon carriage crashes

### ISSUE THREAD

**Issue by ghost** [Cannoneers-of-Create/CreateBigCannons#203]
[crash-2023-05-04_13.48.29-server.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11397054/crash-2023-05-04_13.48.29-server.txt)
[crash-2023-05-04_13.48.42-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11397056/crash-2023-05-04_13.48.42-client.txt)
crash generates reports for both server and client, to recreate build an autocannon on a cannon carriage and set the breach to handheld mode, upon interacting the game will crash and you will be unable to join the world again.

**Comment by rbasamoyai** [comment]
This is a VS issue that I've communicated to the authors, and will hopefully be resolved in the near future.
