### ISSUE TITLE
Confused about Fabric

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [Cannoneers-of-Create/CreateBigCannons#213]
I've seen the Fabric builds on CurseForge, but also the notice at the bottom of the README stating that there will not be a Fabric port.
This confuses me.

Is the README outdated, or has the Fabric port been discontinued? In either case, I think the README should be updated to more accurately reflect what's happening.

**Comment by rbasamoyai** [comment]
Readme is outdated, should be updated

**Comment by rbasamoyai** [comment]
https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/5d078ac0cf65942f9dfcc632cbdcea18759e6c0b fixes this
