### ISSUE TITLE
[1.19.2][Crash] Failed to create player model for default

### ISSUE THREAD

**Issue by coco875** [Cannoneers-of-Create/CreateBigCannons#218]
[crash-2023-05-26_03.15.17-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11570519/crash-2023-05-26_03.15.17-client.txt)
I have also a lot mod of optimisation and the last version of create so a lot of things can break the mod

**Comment by rbasamoyai** [comment]
I see so many different mods in here that target different versions of 1.19.2, so there is not much action I can take. Does removing CBC solve the crash?

**Comment by rbasamoyai** [comment]
edit: what the fuck is this modlist? there's even 1.18.2 mods in here. sorry, can't provide any help.
