### ISSUE TITLE
A Max-sized Cannon Builder Won't React to Redstone Signal for Changing Its State When Fully Extended

### ISSUE THREAD

**Issue by para-dichloro-benzene** [Cannoneers-of-Create/CreateBigCannons#222]
For example, in the default setting of 32-block-range cannon builder, if we attach 32 piston extension poles to the builder, it won't react to the redstone signal for changing its "sticky state" if fully extended. But if we don't fully extend the builder or attach less than 32 poles to it, the redstone signal works perfectly.

If the value "maxCannonBuilderRange" in config file is changed to something different than 32, then all the above statements will still be true once all the "32"s get changed into the value changed into.

**Comment by para-dichloro-benzene** [comment]
Minecraft 1.18.2, Forge 40.2.4, Create 0.5.0.i, CBC beta 0.5.b

All the tests were made in a modpack, but the bug's behaviour does not seem to be a compatiblity issue so I did not test in a vanilla environment.

**Comment by rbasamoyai** [comment]
Could you provide a video on how to replicate this issue?

**Comment by para-dichloro-benzene** [comment]
https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/50518519/1cfd0c82-5ddb-4ffb-baf6-f328d6bdcf10

Heavily compressed for being able to be uploaded directly.

The length of piston pole was 32 at first and 31 at last, "maxCannonBuilderRange" not changed.

Minecraft 1.18.2, Forge 40.2.9, Create 0.5.0.i, CBC beta 0.5.b
