### ISSUE TITLE
Some ideas for major updates.

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#23]
Colorful  **_Powder Charges!_**
Let players kill villagers with style! >:)
_**Pink Powder Charge:**_
![2022-07-27_14 38 40](https://user-images.githubusercontent.com/109973204/181326265-cec8b21f-da59-4ddd-b7f1-881fc8a0df45.png)
_**Yellow Powder Charge:**_
![2022-07-27_15 47 04](https://user-images.githubusercontent.com/109973204/181329787-e5fc3c8b-a327-4d55-bca9-c713a98f8035.png)
_**Cyan Powder Charge:**_
![2022-07-27_16 09 25](https://user-images.githubusercontent.com/109973204/181330657-9c3d6104-b49d-43ce-957d-8dd2a166528b.png)

**_Illuminating Shells:_** Provide us with strong light source, while slowly falling woth parachute.

![IMG_6816-copy](https://user-images.githubusercontent.com/109973204/181340059-ceb909c4-feda-49f6-a5ad-44accaac7f91.jpg)

**_Smoke Shells:_** Just smoke. Btw picture below isn't actually a smoke shell, it just looks cool.
![iowashellpowder](https://user-images.githubusercontent.com/109973204/181341021-e82cd735-0a1b-42ed-96e2-bab1f772db68.jpg)
**_Smoke Screens and Generators!_** When Create: Aeronautics release, it would be very strong and tactical weapon on the battlefield.

![smoke-curtain-navy](https://user-images.githubusercontent.com/109973204/181341528-495c54c0-c94d-40b5-a824-db8cff35a017.jpg)

**_Incendiary Ammunition!_** The smell of **Victory** >:)
https://www.youtube.com/watch?v=nx5N-4JvVyk
_**Edited: Proximity Fuzes. Very usefull against planes and can also be activated above the ground. Set the altitude and fire!**_
![proximity_fuse_mk53_fuze_2158278](https://user-images.githubusercontent.com/109973204/181352565-7de1fe38-93bc-4ac0-9972-abcfbeec5733.jpg)

That's all for now. I hope at least something would be in the future!
*
*
*
*
*
**_Warning! Hacked Secret Data! Do not READ!
C:/Users/rbasamoyai/AppData/Roaming/.minecraft/mods/createbigcannons.jar/data/rbasamoyai\createbigcannons\munitions\gas_shell_block.class_**
////////////////////////////////////////////////
Description: 
**_This Shell made of [DELETED], used against [DELETED] in [DELETED]. Most famous for destruction and it's toxic [DELETED] Color. Can be **Released** like regular smoke from smoke generator.
Effects: [DELETED], destroys nature, [DELETED], [DELETED]._**
_**Pattern: 
[XXX]
[XXX]
[XXX]
_"key":{
           "X":"item:[DELETED]"
}_**_

**C:/Users/rbasamoyai> shutdown /s**

**Comment by rbasamoyai** [comment]
kekw at last one

Check the suggestions channel in the discord though, projectiles are a somewhat tired suggestion and I have noted some suggestions in the pinned table.
