### ISSUE TITLE
Construction of a cannon causes game to crash. [1.18.2] [fabric] [crash]

### ISSUE THREAD

**Issue by BraveCaperCat2** [Cannoneers-of-Create/CreateBigCannons#236]
When constructing a cannon the game crashes.
I had another issue with another mod in the same play session, and i could not upload the latest.log there (file too large) so i doubt it will work here.

**Comment by rbasamoyai** [comment]
Send a crash report, it is much smaller

**Comment by BraveCaperCat2** [comment]
Don't remember which of my Curseforge Profiles the crash happened in - but it was definetly using the fabric version of create like this one and it has this mod:
[crash-2023-06-18_13.47.45-server.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12015408/crash-2023-06-18_13.47.45-server.txt)
[crash-2023-06-18_12.20.18-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12015409/crash-2023-06-18_12.20.18-client.txt)

**Comment by BraveCaperCat2** [comment]
Actually, it's either the wrong installation, or it's the fabric version of #221
