### ISSUE TITLE
[Minor Visual/Performance] Particles still spawn even on minimal particle settings (no optifine)

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#24]
![obraz](https://user-images.githubusercontent.com/71346253/181356080-3625b1cb-e893-4631-851b-c48115b83367.png)

**Comment by rbasamoyai** [comment]
Currently, the most recent nightly has an option to disable plumes outright, could also make it scale in terms of setting.
The option to disable plumes has been in the config since https://github.com/rbasamoyai/CreateBigCannons/commit/29455f14418d73f349a8a451bd394d71498c13f6.
