### ISSUE TITLE
1.19.2 fabric server crash 

### ISSUE THREAD

**Issue by ghost** [Cannoneers-of-Create/CreateBigCannons#245]
log
[log.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/11855596/log.txt)
you dont need more info

**Comment by Zainyest** [comment]
Same, I've also seen this method crash almost every other create addon I've tried in the last few days:
`at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]`

**Comment by ghost** [comment]
> Same, I've also seen this method crash almost every other create addon I've tried in the last few days: `at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]`

Have you find a fix

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/bfb412931bb240e51ce7da2f7075c8df55309808 (1.18.2 branch) and will be ported over to 1.19.2. Will close this issue once porting is done

**Comment by ghost** [comment]
> Fixed in [bfb4129](https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/bfb412931bb240e51ce7da2f7075c8df55309808) (1.18.2 branch) and will be ported over to 1.19.2. Will close this issue once porting is done

Ty

**Comment by ghost** [comment]
> Fixed in [bfb4129](https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/bfb412931bb240e51ce7da2f7075c8df55309808) (1.18.2 branch) and will be ported over to 1.19.2. Will close this issue once porting is done

Is it yet done

**Comment by ghost** [comment]
It has been 3 weeks is it fixed i gues no but yeah

**Comment by ghost** [comment]
[crash.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12064611/crash.txt)
there is log of newest nightly downloads

**Comment by BraveCaperCat2** [comment]
Just wait for the port to finish.
