### ISSUE TITLE
Mod createbigcannons requires flywheel 0.6.8 or above, and below 0.6.9 		Currently, flywheel is 0.6.9-101

### ISSUE THREAD

**Issue by breadlol64** [Cannoneers-of-Create/CreateBigCannons#253]
I have 1.18.2 forge 40.2.4 modpack with create 0.5.1c and create big cannons beta 0.5.b
when i launch (without flywheel) it shows this error message

**Mod createbigcannons requires flywheel 0.6.8 or above, and below 0.6.9
		Currently, flywheel is 0.6.9-101**

**Comment by raimkras97** [comment]
same thing but I'm on 1.19.2
this is what i get in "latest.log"

[18Jul2023 09:32:44.597] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'flywheel', Requested by: 'createbigcannons', Expected range: '[0.6.8,0.6.9)', Actual version: '0.6.9-18'
	
	
[Edit]
downloaded nightly version from discord and all works fine

**Comment by wardeada** [comment]
ami tambien me pasa este problema saben com solucionarlo

**Comment by breadlol64** [comment]
why closed?
