### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by JoshuaMiner37** [Cannoneers-of-Create/CreateBigCannons#254]
Minecraft repeatedly crashes and say that this mod is providing an issue
![Screenshot 2023-07-15 080221](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/139593873/510bff37-731d-4db9-a0ea-697ab04e183f)

**Comment by BraveCaperCat2** [comment]
remove this mod and it should work until a full solution exists.
if you have blocks and items from this mod in your world make sure you make a backup first.
