### ISSUE TITLE
Cannon shells/shots unable to rotate horizontally

### ISSUE THREAD

**Issue by L0Jay** [Cannoneers-of-Create/CreateBigCannons#26]
As said above, the Solid Shot, High Explosive (HE) Shell, Shrapnel Shell, and Bag of Grapeshot blocks are all unable to rotate from their original orientation horizontally, via either a mechanical bearing, or windmill bearing.

 - OS: [e.g. Windows]
 - Version: 1.18.2-nightly-1cdc226

**To Reproduce**
1. Get any of the cannon Shells/Shot + a mechanical bearing and hand crank.
2. Place whatever shell/shot you grabbed in a way so that it looks like it's on it's side, then place your mechanical bearing on top or underneath it with the sticky side facing the shell/shot, and use the hand crank to turn it.
3. The shell/shot will appear to turn, but once you stop, it will snap back to it's original orientation.

Expected behavior
Of course one would expect the shell/shot to rotate and not snap back, especially since you're able to rotate Powder Charges just fine, it's only a minor bug though, that only comes into play when you either place the shell wrong or when a deployer that's moving on a contraption places it.

https://user-images.githubusercontent.com/110139400/181395286-2b184317-5dbb-4176-9c9b-f588bcd8db4d.mp4

(Sorry if this report wasn't very clean or concise, I literally just got a github account 30 minutes ago)

**Comment by rbasamoyai** [comment]
Yeah, i've noticed this. Not sure why projectile munitions aren't rotated

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/rbasamoyai/CreateBigCannons/commit/28492979f4d11428587f8e196cfb4a10219323cd.
