### ISSUE TITLE
Ammo box config not working correctly

### ISSUE THREAD

**Issue by glougloudu77** [Cannoneers-of-Create/CreateBigCannons#276]
Good morning
the config which allows you to modify the quantity of cartridge in the ammo box is blocked at 64, in the config it is written that you can put a value between 0 and 128 but even when you put the config at 128, you cannot can't put more than 64 in the box,
moreover, the FOV bug has still not been fixed

**Comment by rbasamoyai** [comment]
The 128 limit only works if you store ammo in both the main ammo slot and the tracer slot.
Also, what FOV bug?

**Comment by glougloudu77** [comment]
totute mes excuses pour m'etre tromper, pour ce qui concerne le bug de FOV, lorsque le mod est installé, la config des effet de FOV se bloque a 100%, la config affiche 0% mais les effet reste present dans le jeu

**Comment by rbasamoyai** [comment]
Could you record a video demonstrating this?

**Comment by rbasamoyai** [comment]
never mind, found out what the issue is. will address it
