### ISSUE TITLE
Planned Method for 0.5.1 Compattibility:

### ISSUE THREAD

**Issue by BraveCaperCat2** [Cannoneers-of-Create/CreateBigCannons#298]
Stop using the depreciated (and in 0.5.1, removed) method known as com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)
(pulled from a minecraft log as the game crashed of 0.5.1 incompatibility)
with com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.create(java.lang.String) (i think that's what it was called)
mentioned as CreateRegistrate#create which replaced CreateRegistrate#lazy

**Comment by rbasamoyai** [comment]
Already fixed a long time ago, all incompatibilities have been addressed and the mod is just sitting around to be released. The only main thing that's holding back release is that I'm just waiting for anyone else to submit localization, but I'll likely release CBC 0.5.2 around Friday.

**Comment by BraveCaperCat2** [comment]
didn't know that.

**Comment by BraveCaperCat2** [comment]
now all i need to do is repeat this message for all the other create addons.
