### ISSUE TITLE
Create Big Cannon requiring UNEXISTING mods

### ISSUE THREAD

**Issue by MrDesigner-Official** [Cannoneers-of-Create/CreateBigCannons#300]
I have a modpack in 1.18.2 with a ton of create add-ons and Create Big Cannons is Requiring "Flywheel 0.6.9" a mod that DOES NOT exist now.

How can I solve the issue?

**Comment by rbasamoyai** [comment]
uninstall FLW, latest Create has flywheel 0.6.9 already in the mod. also if you're not already, use the latest nightlies from the discord. a release version of Create Big Cannons 0.5.2 will be out soon
