### ISSUE TITLE
[Feature] Additional cannon mounting options

### ISSUE THREAD

**Issue by luca-0x** [Cannoneers-of-Create/CreateBigCannons#310]
Is your feature request related to a problem? Please describe.
The 3 block height of the cannon mount and the forced orientation limits creativity and doesn't fit in small contraptions.
Last but not least, it also makes it impossible to stack multiple cannons vertically, wich would create a whole lot of new design possibilities.

Describe the solution you'd like
I see 2 possible additions that combined would allow all kind of designs:

- **Upside down mounts** and **side mounts** (the latter is especially useful since would allow to stack cannons vertically)
- **Fixed compact mounts**: 2 blocks tall mount that can't move the cannon (why? sometimes movement is not needed but space is a costraint, an example of this are airship mods: when the cannons are mounted inside of airships you can aim by moving the whole ship)

Visual example of side mounts with vertically stacked cannons:
![vertical cannons](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/16616566/4f45506e-3ecb-413e-9d3b-f5b49c1efabc)

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by rbasamoyai** [comment]
Fixed cannon mounts are planned as well as upside down mounts. I am more concerned about side mounts as I am not sure what the best control scheme for them would be.

**Comment by Puggicorn** [comment]
I'd love a fixed mount or otherwise the ability to fire a cannon that isn't on a mount at all by using a flint and steel or redstone. Particularly for possible automated defense systems using some kind of redstone sensor and clever tuning

**Comment by rbasamoyai** [comment]
Note: a derivative of side mounts is being made in an addon for CBC. I will not link to it here; search up "side mounts" in the CBC discord if that is of interest.

**Comment by AngelOfCreation** [comment]
Bump. Definitely want this added. Then I'll finally be able to add an array of auto turrets under my helicarrier when Aero comes out.

**Comment by rbasamoyai** [comment]
Upside down mounts and Fixed Cannon Mounts implemented in #712, #713, and #714. Regular side mounts will not be implemented.
