### ISSUE TITLE
Integration with Display Link from Create Mod

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#32]
_**Measuring Deegrees.**_
I think this will help players make the artillery like IRL. 
I have 2 solutions: 
**1. Make the display link measure degrees. It will be attached on Cannon Mount and Yaw Controller. (Simplier)** 
![2022-07-28_14 41 58](https://user-images.githubusercontent.com/109973204/181512380-a065416b-4546-4471-963e-67e160b6fd96.png)
**2. Make the new block like stressometer and speedometer, that will aslo be measured by display link, It will measure not just cannon position, but all Create Contraptions. (Harder)** 

 But there is a **problem**: -Developers of **Create: Aeronautics** can make protractor block too. _**But if they wouldn't make it**_, and you make it, i suppose **_more people would download your mod_** because of that _(sorry, i didn't mean to say that protractors better than your mod)_.
/
And the last thing: **_-Artillery Compass_**. It would be like regular compass IRL, but it will show you degrees where you look at. Like when you look at north-east it will say: **_North-East 135°_**
I think it would made of compass and precision mechanism, and looks loke golden compass (or at least with golden crops on its texture)

**Comment by BraveCaperCat2** [comment]
if the mod worked it would be great, but I'm uncertain the mod works right now.

**Comment by MrSerafim** [comment]
i think that would be great, also it would be nice if the mod gave more information to calculate the external ballistics of the shell, like muzzle velocity por charge and shell type, weigth of the shell, also a sight with some data like the angle.

**Comment by rbasamoyai** [comment]
https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/e05738f378b94bae340604793d506e72f10205b9

Finally implemented it here.
