### ISSUE TITLE
[1.19.2, Forge] Fluids show up as fluid_type.unregistered_sadface in JEI/REI

### ISSUE THREAD

**Issue by Evan555alpha** [Cannoneers-of-Create/CreateBigCannons#345]
Title. Nothing game-breaking as far as I can tell, but an annoyance nonetheless.
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/10338511/84a0c5c8-4eb3-4fe3-a13d-101a21c431d2)

[Latest.log](https://mclo.gs/xlxvKPd)

Forge 43.2.21
[✔] alloyed-1.19.2-v1.5a
[✔] architectury-6.5.85-forge
[✔] cloth-config-8.3.103-forge
[✔] create-1.19.2-0.5.1.c
[✔] createbigcannons-forge-1.19.2-0.5.2
[✔] RoughlyEnoughItems-9.1.650

**Comment by rbasamoyai** [comment]
Was already fixed in this commit (1.19.2) https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/a9c804dbfc219c9c6f4aae9f6dc7519a47144536 and propagated to 1.20/dev

**Comment by Evan555alpha** [comment]
My apologies - I should have checked the recent commits first.
