### ISSUE TITLE
Bronze cannon didn't rupture with 7 powder charges

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#35]
![obraz](https://user-images.githubusercontent.com/71346253/181528413-61baf4c9-db52-4612-ab9e-1f17f3db9e17.png)
this cannon can safely fire with excess powder charges

**Comment by rbasamoyai** [comment]
How many times did you try it? Could've been lucky, I'll check the code though
