### ISSUE TITLE
Incompatible with create 5.1e

### ISSUE THREAD

**Issue by Syclusion** [Cannoneers-of-Create/CreateBigCannons#356]
Newest update to create causes cbc to crash on launch.

[crash-2023-09-28_16.25.49-fml.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12753685/crash-2023-09-28_16.25.49-fml.txt)

**Comment by rbasamoyai** [comment]
Known issue

**Comment by Camawama** [comment]
Unsure if this relates but I have create 0.5.1.e and I am not getting a crash report but the game crashes.

[latest.log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12811617/latest.log)

**Comment by Syclusion** [comment]
> Unsure if this relates but I have create 0.5.1.e and I am not getting a crash report but the game crashes.
> 
> [latest.log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12811617/latest.log)

net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: createbigcannons, class rbasamoyai.createbigcannons.forge.CreateBigCannonsForge
java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	at rbasamoyai.createbigcannons.forge.ModGroupImpl.useModTab(ModGroupImpl.java:38) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23458!/:?]
	at rbasamoyai.createbigcannons.ModGroup.useModTab(ModGroup.java) ~[createbigcannons-forge

From your log. It's the same issue.... not quite sure why you had to ask in the first place lol. If your using cbc and create e its gonna crash, it's not gonna work until that is updated. Until then you can build the pull request as a temporary fix.

**Comment by codec-d** [comment]
instead of creating a new issue I'll just bump this one

**Comment by Erabior** [comment]
Also going to bump this instead of making a new issue. getting the same exception as the one posted above

**Comment by Camawama** [comment]
bump

**Comment by rbasamoyai** [comment]
Fixed, will be released in next update
