### ISSUE TITLE
Crash when placing cannon leyer

### ISSUE THREAD

**Issue by Juff-Ma** [Cannoneers-of-Create/CreateBigCannons#359]
The game crashes when using one of the cannon layers required for crafting the higher tier cannons.

[crash report](https://bytebin.lucko.me/ro3oY1zGNo)

**Comment by rbasamoyai** [comment]
Known issue and will be fixed in an upcoming PR

**Comment by CSdiscoveries** [comment]
Same issue. As well, the world in which I placed the block now immediately crashes if I try to load it.
