### ISSUE TITLE
Compatibility issues with CreateCannons and valkyrienskies mod for 1.18.2

### ISSUE THREAD

**Issue by JinxedGamer** [Cannoneers-of-Create/CreateBigCannons#361]
Making a pirate themed modpack and I need cannons but valkyrienskies and Cannons appears to have some compatability issues if there is a way to resolve this that would be great
[crash-2023-10-01_20.00.25-fml.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12778566/crash-2023-10-01_20.00.25-fml.txt)

**Comment by rbasamoyai** [comment]
Known issue, Valkyrien Skies needs to update their stuff. For now you can downgrade Create Big Cannons to 0.5.1.b and Create to 0.5.0.i
