### ISSUE TITLE
Pondering crash

### ISSUE THREAD

**Issue by Vandorsolyom** [Cannoneers-of-Create/CreateBigCannons#363]
Error: java.lang.NoClassDefFoundError: com/simibubi/create/content/kinetics/fan/FanProcessing$Type
I got this error while trying to ponder "finishing built-up cannons".  
[crash-2023-10-03_14.51.46-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12792639/crash-2023-10-03_14.51.46-client.txt)

**Comment by rbasamoyai** [comment]
Known issue and will be fixed
