### ISSUE TITLE
Javalang no such method error

### ISSUE THREAD

**Issue by Kurbatishche** [Cannoneers-of-Create/CreateBigCannons#368]
Create Big Cannons (createbigcannons) has failed to load correctly 
javalang.NoSuchMethodError: ‘com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)’

**Comment by abacaxiFlamejante** [comment]
Same error here.

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/357
