### ISSUE TITLE
Create Update Crashing

### ISSUE THREAD

**Issue by mxnmnm** [Cannoneers-of-Create/CreateBigCannons#382]
Create updated to 0.5.1.f and this addon causes it to crash. Here is the crash report https://gist.github.com/mxnmnm/0f7da1de2f320b5c781c316ca9b3e076

**Comment by funrider28** [comment]
can confirm this is a valid issue

**Comment by Nycto97** [comment]
Yes, updated Create as well as some add-ons for Create (have around 20 or so) and server fails to load.
Narrowed down the cause to Big Cannons mod. [Crash log](https://pastebin.com/A5eUSEj9)

**Comment by Karolon** [comment]
i have similar problem

**Comment by abershadow2000** [comment]
Same here

**Comment by rbasamoyai** [comment]
Fixed in 0.5.3
