### ISSUE TITLE
Ballistic trajectory of the projectile

### ISSUE THREAD

**Issue by Mikivan099** [Cannoneers-of-Create/CreateBigCannons#386]
Hi, I would like to know by what formula you can determine the range of a projectile shot, if I know the angle of the shot and the velocity of the projectile, m/s, I tried a lot of calculations and could not calculate even close, especially if you use a powder charge of 4 powder flasks (80 m/s) all the others fluctuate in within my calculations, but it's not enough. I would like to create create a point firing with an acceptable spread

**Comment by zoeyrhine** [comment]
Sorry, why is this marked completed with no answer? I too would like to know the formula
