### ISSUE TITLE
game crashing when I ponder the cannon builder

### ISSUE THREAD

**Issue by whillo** [Cannoneers-of-Create/CreateBigCannons#387]
video of the issue
https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/60895902/baaf6f07-923d-4fa8-8397-6f01f94ba7fd
game logs
[crash-2023-11-12_12.31.36-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13327849/crash-2023-11-12_12.31.36-client.txt)

**Comment by rbasamoyai** [comment]
Fixed in 0.5.3
