### ISSUE TITLE
Create Big Cannons latest version Incompatibility with Create

### ISSUE THREAD

**Issue by NikoTheGreat** [Cannoneers-of-Create/CreateBigCannons#388]
It appears that there is an incompatibility with the latest version of the Create Big Cannons and the base Create mod. Startup with both mods causes the game to crash.

**Comment by NikoTheGreat** [comment]
I'm using Curse Forge to test mods. See picture below for test scenario:
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/16003271/913d5707-fe47-41b0-916a-d717207f417a)

**Comment by NikoTheGreat** [comment]
Here is the crash FML:
[crash-2023-11-13_11.10.31-fml.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13337571/crash-2023-11-13_11.10.31-fml.txt)

**Comment by NikoTheGreat** [comment]
Here is the Log:
[latest.log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13337572/latest.log)

**Comment by NikoTheGreat** [comment]
I will notify of other incompatibilities if another test scenario fails.
I love your mod, it is tons of fun! Keep up the good work!   =)

**Comment by rbasamoyai** [comment]
Fixed
