### ISSUE TITLE
[Forge 1.20.1] Unexpected Crash

### ISSUE THREAD

**Issue by Starexify** [Cannoneers-of-Create/CreateBigCannons#389]
Minecraft Version: 1.20.1
Forge Version: 47.2.5
Mod Version: 1.20.1-0.5.2a

Crash Log: https://pastebin.com/FVXNJqcr

No idea, tbf maybe Create 0.5.1f isnt compatible?

**Comment by PatTheWizard** [comment]
Yea it is not compatible with create 0.5.1.f

**Comment by rbasamoyai** [comment]
Fixed in 0.5.3

**Comment by hydroakri** [comment]
still unexpected crashed
mod version: 0.5.3b/0.5.3
1.20.1-forge 47.1.97
