### ISSUE TITLE
[IDEA] Smoke from the barrel after firing

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#39]
![obraz](https://user-images.githubusercontent.com/71346253/181574437-198a559c-df81-4d5c-a6d3-2ffa8fc92a52.png)

**Comment by rbasamoyai** [comment]
yeah, not too partial to more effects for the cannon plume, might add.

**Comment by Abrams11IsBack** [comment]
yeah maybe as an overheating mechanic

**Comment by Abrams11IsBack** [comment]
> yeah, not too partial to more effects for the cannon plume, might add.

it would smoke for a couple of seconds after too many shots and then you could fire it again

**Comment by rbasamoyai** [comment]
Oh yeah, I have definitely considered overheating ~just to put a cap on these blazing saddle autoloaders~ but yeah might be a configurable feature.
