### ISSUE TITLE
[1.19.2] Crash and chunkban caused by Built up cannon layers

### ISSUE THREAD

**Issue by MaximilienMoritz** [Cannoneers-of-Create/CreateBigCannons#391]
Built up cannon layers crash the game, as well as cause a chunkban.

Crash log : [https://pastebin.com/c6hDKuLx](https://pastebin.com/c6hDKuLx)

**Comment by rbasamoyai** [comment]
Sorry for getting to this late, but could you repost the crash log here if possible? As well, please detail how you got this issue.

**Comment by ImVeryBadD** [comment]
Can recreate by placing any cannon layer in a world, or stopping a mechanical bearing with it if its a survival mode. 1.19.2, big cannons 0.5.2.a-nightly-b379602, create 0.5.1.e 
[crash-2023-12-04_22.03.34-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13550361/crash-2023-12-04_22.03.34-client.txt)

**Comment by rbasamoyai** [comment]
Use the latest CF version (0.5.3) and Create 0.5.1.f
