### ISSUE TITLE
Suggestion - Upside-down cannon mounts

### ISSUE THREAD

**Issue by Veylyn** [Cannoneers-of-Create/CreateBigCannons#392]
Was considering a project with a hanging cannon and was disappointed to find this wasn't currently possible. Would be neat if the cannon mounts could be placed upside-down, or otherwise rotated, so the cannon pivot is below the block itself

**Comment by rbasamoyai** [comment]
Planned for a later version.

**Comment by WorldsOfRosefire** [comment]
good idea. sideways too.

**Comment by rbasamoyai** [comment]
Finally implemented as of #712, #713, and #714
(Edit: No sideways mounts, not planned)
