### ISSUE TITLE
Incompatibility with ParCool

### ISSUE THREAD

**Issue by cloby0** [Cannoneers-of-Create/CreateBigCannons#410]
Minecraft: 1.19.2
Forge: 43.3.0

Create: 0.5.1.f
CBC: 0.5.3-nightly-d26788b
ParCool: 1.19.2-3.1.0.4-R

Steps to recreate:

1. Have all the aforementioned installed
2. Load a world of any variety
3. Press 'a' & 'd' at the same time

Description: 
Loading both CBC and ParCool breaks everything in ParCool which uses screen-rotation forwards and backwards (flipping, dodge rolls, etc.)

**Comment by rbasamoyai** [comment]
Could you provide a video of the faulty behavior?

**Comment by cloby0** [comment]
https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/76920325/02b2a2ab-ed17-4931-9b22-5d139f0af0fb

it's a little laggy but i think you might be able to get the idea

**Comment by rbasamoyai** [comment]
I'm trying to recreate this now, in dev env I can't seem to, at least on 1.18.2. Could you try ParCool! and CBC in isolation (with appropriate dependencies)?

**Comment by rbasamoyai** [comment]
this may have been fixed somewhere along the way, not sure where

**Comment by rbasamoyai** [comment]
Can recreate this in 1.19.2, spoke too soon

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/438, will close on 0.5.3.b release
