### ISSUE TITLE
Latest build of Create Big Cannons is not compatible with Quilt

### ISSUE THREAD

**Issue by Sunconure11** [Cannoneers-of-Create/CreateBigCannons#412]
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/5614902/2e936ba6-7839-42e3-85c8-10882972b8d4)

**Comment by rbasamoyai** [comment]
Is there no Quilt 0.76.1?

**Comment by Sunconure11** [comment]
Correct

**Comment by rbasamoyai** [comment]
Does just Create run?

**Comment by rbasamoyai** [comment]
Seems like Create uses 0.76.0, will make the downgrade

**Comment by rbasamoyai** [comment]
Fixed recently in 0.5.3.a
