### ISSUE TITLE
Steel ingots just not existing.

### ISSUE THREAD

**Issue by foehawked** [Cannoneers-of-Create/CreateBigCannons#413]
Version of mod: 0.5.2.a (and 0.5.3) for fabric with 0.5.1.d create fabric on Minecraft 1.20.1

So, I have been messing around with the big cannons mod for a while now, but only now have I decided to try to actually create a cannon creator. I soon ran into a problem though, which was that I just couldn't find steel ingots anywhere. When I used to play it a while back, I swore there was steel ingots and that's how you make liquid steel, not shrapnel. I am confused by this as I'm not using any other mods that should conflict, but if I am I will include a list of the mods I'm using too.

Images:
![Screenshot 2023-12-04 191401](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/123910317/1b7ee19a-6b89-4b3e-9a2a-2d2bb47b1070)
above: only being able to create molten steel via shrapnel

![Screenshot 2023-12-04 191112](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/123910317/fed8a1ec-17bf-417b-8f28-701e8dba5238)
above: unable to create nethersteel as one of the ingredients is just gone. (it's the steel)

![Screenshot 2023-12-04 191532](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/123910317/3a47d816-3690-4ffc-af68-2b94076c6fcf)
above: literally a screenshot of my mods folder. That's all the mods I have loaded.

I am not good at Java coding at all so I have no idea why it's like this but I hope it's fixable.

EDIT: I changed my mod to 0.5.3 to see if the bug remained, and it did.

**Comment by rbasamoyai** [comment]
Steel was never added outside of scrap. The initial idea was to have the player use other mods adding bronze and steel, namely Create: Alloyed, to source the material. I am aware that it does not have a 1.20.1 version. For now, any mod that adds steel tagged correctly should work.

CBC will add its own steel and bronze in the future, but not in the next release, which as of this writing will be 0.5.3.b. Also, a less efficient nethersteel recipe based on cast iron already exists.

**Comment by foehawked** [comment]
Thank you so much for your reply, I did not realize that at all. I will try to experiment with some other mods to see if their steels and bronze would work, but other than that I guess I'll wait until either this mod adds steel or Create: Alloyed finally updates.
Once again, thank you!

**Comment by DefomCode** [comment]
so the developer just refused to add the ingots because he thinks the player will find them in other mods? fucking nonsense

**Comment by rbasamoyai** [comment]
The justification is that I wanted to avoid adding more ingots and ores. Cast iron and nethersteel got ingots because they are unique enough, but I feel like bronze and steel felt quite ubiquitous. Also, the mod was first made when Create: Alloyed was pretty notable.

Edit: on ores, I wanted to add tin to make bronze. I know Alloyed did not do that but zinc for bronze did not sit well with me at the time. In any case, this will all change in a future version.
