### ISSUE TITLE
Incompatibility with Shoulder Surfing Reloaded (1.19.2)

### ISSUE THREAD

**Issue by ToppyTopology** [Cannoneers-of-Create/CreateBigCannons#419]
While create big cannons is installed in a new or old world, the player will turn invisible and breaks its shoulder camera (the camera is centered like in vanilla third person).

![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/103081806/c5e0bf2a-1a3f-4c66-afdf-4eea0b5f8a39)

The only mods I have installed are:

create-1.19.2-0.5.1.f.jar
createbigcannons-forge-1.19.2-0.5.3.jar
ShoulderSurfing-Forge-1.19.2-2.8.1.jar

[create big cannons shoulder surfing logs.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13700315/create.big.cannons.shoulder.surfing.logs.txt)

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/438, will close this issue on 0.5.3.b release
