### ISSUE TITLE
[1.18.2 Forge] Server crash as unable to load for some reason

### ISSUE THREAD

**Issue by TqLxQuanZ** [Cannoneers-of-Create/CreateBigCannons#421]
After updating to create big cannons from 0.5.2a to 0.5.3, the server seems to always crash upon loading. Is there anything am I missing for dependency?

[crash-2023-12-24_00.11.15-fml.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13759592/crash-2023-12-24_00.11.15-fml.txt)

**Comment by rbasamoyai** [comment]
Use the latest version of Create (0.5.1.f)
