### ISSUE TITLE
Crash on cannon fire, but not every time

### ISSUE THREAD

**Issue by VivianneAleksander** [Cannoneers-of-Create/CreateBigCannons#427]
I'm not sure what the specifics of what causes this are, but sometimes when I click to fire a cannon using the cannon carriage, the game CTDs and bricks the save. I'm investigating further to try and get more details.

Minecraft v1.19.2, Quilt v0.22.0, CBC v0.5.3.a, Create v0.5.1.b, and Quilted Fabric API v4.0.0. Crash log pastebin below.

https://pastebin.com/54gAVjmY

**Comment by rbasamoyai** [comment]
Known issue, fixed in latest nightly. Will close on 0.5.3.b release
