### ISSUE TITLE
Cannot load world because of Create Big Cannons Error

### ISSUE THREAD

**Issue by tartyto** [Cannoneers-of-Create/CreateBigCannons#433]
It first crashed after firing a cannon on a cannon carriage and then the same crash happens when loading the world, i lost that world.
It says:

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot read field "f_74676_" because "breech" is null

[Crash Log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/13802311/log.txt)

**Comment by rbasamoyai** [comment]
Duplicate of #427, fixed and will be closed on 0.5.3.b release
