### ISSUE TITLE
Required incompatible fabric api with Create Fabric

### ISSUE THREAD

**Issue by gundami** [Cannoneers-of-Create/CreateBigCannons#444]
The latest fabric version of CBC required 0.89.3, but Create Fabric only support 0.88.1. As the result, the latest CBC cannot work with Create on 1.20.1.

**Comment by rbasamoyai** [comment]
Will address this in a later patch/minor version for CBC

**Comment by Sepera-okeq** [comment]
I agree, this has a problem. Because the problems associated with the fapi version Create, as well as other mods (for example, sodium, which does not work normally for version 0.5.x+ with Create (fapi 0.88.1)

**Comment by MaxenceDC** [comment]
Yes, that'd be really great. In the meantime, it's possible to use an older version (0.5.2)

**Comment by rbasamoyai** [comment]
This has been fixed in the latest indev version and will be closed on the next release.
