### ISSUE TITLE
Recipe output missing from molten steel compacting recipe

### ISSUE THREAD

**Issue by JpnRndr01** [Cannoneers-of-Create/CreateBigCannons#445]
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/43012044/d0a6fd0a-01f9-427d-8637-e8878efba191)

There is no steel ingot output for this recipe, also there is no steel nugget version of the recipe

**Comment by rbasamoyai** [comment]
Install a mod with steel, such as Base Metals

**Comment by rbasamoyai** [comment]
CBC will add its own steel and bronze in the future.
