### ISSUE TITLE
Cannon Casting additions and changes via Datapack

### ISSUE THREAD

**Issue by drhaber** [Cannoneers-of-Create/CreateBigCannons#446]
Cannon Casting is a really wonderful mechanicand it would be really awesome to be able to add on to it with custom moulds and fluids and outputs using datapacks

**Comment by rbasamoyai** [comment]
Custom casting recipes with pre-existing moulds is already possible. However, custom moulds are relegated to either KubeJS (which won't be great, as it is dropping Fabric support in later versions) or making an addon mod.
