### ISSUE TITLE
Azimut display/Ball spread

### ISSUE THREAD

**Issue by JavaBoii** [Cannoneers-of-Create/CreateBigCannons#448]
i am currently working on a working artillery computer program. The code is working as needed in ComputerCraft. But one thing that is making my life incredibly difficult is:
A - knowing/setting the azimut of the cannon
B - knowing/setting the elevation of the cannon

Since minecraft doesnt use 360° but +-180° -> +-0°
its not as easy as just putting in the heading.
So i just put the Gun as close as i could to 135° and did some fire testing:
![grafik](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79570962/18a25820-25ab-4968-8f19-92394f6c52cf)

![grafik](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79570962/e6164796-afe9-4719-8560-ab009e081918)

up to 80m/s (8) shots everything was alligned with the target (T) from the start (S). But as soon as i arrived at 120m/s charges. The spread became as large as 40x40 block area. The impact was just 240m away.
At 160m/s the spread rose to 100x100 block area.  
These were just 
![grafik](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79570962/18be7190-8035-482b-94ce-d6ff41b4e907)
away.

Imo that spread is a bit too targe. I would get it if it was 1 km away. But just 300+ meters? Was this intentional?

On another note, my question is: Since the cannon is probably an entity, Could you add its Yaw data as an output or atleast display? Or a similar mechanic. 

I haven't had time to time and calculate the degrees of rotation/s on each tick, but it would be really really helpful if the model of the cannon had an iron sight that is just a pixel wide at the front and back so i may know when the gun alligns with my reference point.

(optional) It would be really cool if you could set the elevation and azimut with degrees, through external input or a new block.

And also thank you for creating this mod. Had a ton of fun so far.

**Comment by rbasamoyai** [comment]
CBC has minimum spread, which is configurable through the config menu as of 0.5.3.b.
Fire directing features are planned for a future version once Create 0.6.0 releases.
