### ISSUE TITLE
Autocannon Flak Rounds lack some configuration

### ISSUE THREAD

**Issue by benjaminiserman** [Cannoneers-of-Create/CreateBigCannons#454]
Autocannon Flak Rounds always cause an explosion of `2.0f` power. This value should be configurable within `flak_autocannon.json`

**Comment by rbasamoyai** [comment]
sure, why not

**Comment by rbasamoyai** [comment]
Added in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/489
