### ISSUE TITLE
[1.18.2 Forge]Drill Cannon Crafting is incompatible with Create: Interactive

### ISSUE THREAD

**Issue by ghost** [Cannoneers-of-Create/CreateBigCannons#455]
after drilling, unbored cast iron cannon barrel will not turn in to cast iron cannon barrel
cast iron nugget will still produce

**Comment by rbasamoyai** [comment]
Use the latest version of Create Interactive on Modrinth: https://modrinth.com/mod/interactive. If the issue persists, report it to the Interactive devs in the VS2 Discord.
