### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by nul666lun** [Cannoneers-of-Create/CreateBigCannons#460]
[crash-2024-02-22_01.00.29-client.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/14370262/crash-2024-02-22_01.00.29-client.txt)
installed Create.. loads.. installed this mod (and several older versions of this mod back to back and all instantly crash the game before the "Mahjong" splash screen even appears..

**Comment by rbasamoyai** [comment]
Update Valkyrien Skies 2 to a more modern version
