### ISSUE TITLE
Shell position calculations lose accuracy as speed increases

### ISSUE THREAD

**Issue by shuangfas** [Cannoneers-of-Create/CreateBigCannons#461]
160m/s:
![160](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/131521386/e10a2191-068f-43c4-af12-364d3bab378a)
40m/s
![40](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/131521386/9d99195b-2e0f-435c-8266-9c6672834d57)

**Comment by rbasamoyai** [comment]
Aware of this, the block should have actually hit. The reason why this is a thing is because the current projectile system is somewhat imperfect.

**Comment by rbasamoyai** [comment]
Largely fixed in #566
