### ISSUE TITLE
Cannon builder bug

### ISSUE THREAD

**Issue by im-very-tired** [Cannoneers-of-Create/CreateBigCannons#463]
cannon builder cant push multiple layer blocks in a row. ver 0.5.3b
![2024-02-26_19 35 10](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/141376794/ad2a485d-8173-478e-936d-021980c47eda)

**Comment by im-very-tired** [comment]
cant upload modpack to here because of size restrictions

**Comment by FranFkntastic** [comment]
https://github.com/FranFkntastic/Fran-Behaviour-2/tree/main/mods

relevant modpack

**Comment by FranFkntastic** [comment]
reach out to me @franfkntastik on discord for quicker replies

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/488. Will be closed on next release.
