### ISSUE TITLE
Bullets will hit their own plane

### ISSUE THREAD

**Issue by Ixqw123I** [Cannoneers-of-Create/CreateBigCannons#465]
When the plane is traveling at high speed, bullets shot from the plane will hit the plane itself.Even at very fast speeds, bullets fired from the aircraft can hit something behind the barrel.This situation occurred once before when it hit the wooden barrel next to the barrel that was feeding it bullets, but I didn't record it.My English is not good, so I used a translator.If the expression is not accurate, please forgive me.
I originally recorded a video, but it was too large to upload. I can only explain it in the form of pictures.
1，The first and second pictures show the structure of the airplane
![Screenshot_2024-03-08-01-22-35-770_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/eb0c5a1b-d2e2-49b9-9b3c-4478b725e1fb)
![Screenshot_2024-03-08-01-22-48-543_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/11723ff1-d44b-49bb-a9fa-c466aa21ed99)
2，The third picture shows the aircraft rotating its propellers and firing on the ground, operating normally
![Screenshot_2024-03-08-01-23-05-276_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/18c814d1-4a6d-40e1-a86a-212d63975b3d)
3，In the fourth picture, I flew high into the air and began to dive to achieve fast speed
![Screenshot_2024-03-08-01-23-18-269_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/a9caff34-a490-43cd-a7fa-d56795d54579)
4，The fifth picture, I dive and fire
![Screenshot_2024-03-08-01-23-35-513_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/fc4fafc1-f4db-4863-9137-c15c0f247a75)
5，The sixth picture shows that the propeller of the plane has stopped rotating, and I can only control the plane to land. Upon inspection, it was found that the interior of the plane was damaged by bullets
![Screenshot_2024-03-08-01-23-52-060_com miui mediaviewer](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/162611504/c23b8b6f-3d6c-47ba-9203-ae225404eb44)
Is it because the speed of bullets is fixed that when my plane exceeds the speed of bullets, I will be injured by the bullets I shoot?
A loyal fan of your mod
Thank you for reading

**Comment by rbasamoyai** [comment]
This is a Valkyrien Skies issue, please notify them of this.
