### ISSUE TITLE
Create Big Cannons is incompatible with the latest build of Create

### ISSUE THREAD

**Issue by Sunconure11** [Cannoneers-of-Create/CreateBigCannons#467]
Just what it says on the tin, it causes a crash.

**Comment by rbasamoyai** [comment]
This is known and will be addressed soon -- I assume your version is Create Fabric 0.5.1 patch F, which Create Big Cannons Fabric is not yet compatible with.

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/468, issue will be closed next release
