### ISSUE TITLE
Use Fluid Tags Consistently

### ISSUE THREAD

**Issue by petrolpark** [Cannoneers-of-Create/CreateBigCannons#469]
[Some](https://github.com/Cannoneers-of-Create/CreateBigCannons/blob/1.20/dev/forge/src/generated/resources/data/createbigcannons/block_recipes/unbored_steel_screw_breech.json) recipes do use fluid tags. [Some](https://github.com/Cannoneers-of-Create/CreateBigCannons/blob/1.20/dev/forge/src/generated/resources/data/createbigcannons/block_recipes/unbored_steel_autocannon_barrel.json) don't, and only work with CBC fluids. It would be better for compatibility if all recipes used tags. I'm also not sure the `c` namespace for mod-common tags is very popular compared to `forge`, for mods using Forge.

**Comment by rbasamoyai** [comment]
Seems like I missed a beat on these ones, will fix them

**Comment by rbasamoyai** [comment]
also: must've messed up the system I was using for tags in 1.20.1 datagen, as that exclusively uses Fabric but has a flag to switch Forge and Fabric DG.

**Comment by rbasamoyai** [comment]
Fixed in latest indev version and will be closed on the next release.
