### ISSUE TITLE
[1.18.2] Crashes when assembling Create Big Cannons autocannon

### ISSUE THREAD

**Issue by TqLxQuanZ** [Cannoneers-of-Create/CreateBigCannons#470]
Mod Version: 1.18.2 - 0.2.1 - https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat/files/4631182
CreateBigCannons Version: 1.18.2-0.5.3.b

Apparently, whenever you're trying to assemble the autocannon using cannon mount. The moment you pull down the lever to assemble them, the game crashes.
It does not crash if played without flw compat.

**Comment by rbasamoyai** [comment]
Can you send a crash report?

**Comment by rbasamoyai** [comment]
Going to presume that this is resolved and will close this issue. If this is not the case, please open a new issue with more information about your issue.
