### ISSUE TITLE
Steel and bronze not existing 

### ISSUE THREAD

**Issue by Coolthingiguess** [Cannoneers-of-Create/CreateBigCannons#474]
At current state, newer versions of the mod do not have steel and bronze ingots, making cast iron the highest available tier of cannon. They seem to have existed in previous versions of the mod, so I’m not sure why they don’t anymore. Is there an api I’m missing?

**Comment by rbasamoyai** [comment]
CBC currently requires steel and bronze from another mod. IngotCraft is recommended: https://www.curseforge.com/minecraft/mc-mods/ingotcraft
