### ISSUE TITLE
Boundary Box of big cannons entity is too big

### ISSUE THREAD

**Issue by shuangfas** [Cannoneers-of-Create/CreateBigCannons#480]
Will affect other mod's raycasts

**Comment by rbasamoyai** [comment]
It's a contraption entity, so raycasts aren't really affected. If you could provide a mod example where this is a serious issue then please provide one - however, I would argue this is largely a Create issue if that is the case.

**Comment by xiewuzhiying** [comment]
https://github.com/SuperSpaceEye/Some-Peripherals/

**Comment by xiewuzhiying** [comment]
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/92735961/180feb07-e541-439e-8c98-2ae396b0e865)
Like this
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/92735961/b6b29cad-b98f-491f-bf6f-e3aad16ee8ee)

**Comment by rbasamoyai** [comment]
Try it with a Create contraption, specifically the bearing contraption - you'll see that it's the same issue there. There could be a way of making the hitbox dynamically scale, but ultimately it would largely just be mostly empty space.

Also, what mod is this?

**Comment by xiewuzhiying** [comment]
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/92735961/18aac11f-d981-44d5-8a04-a2d28d7ef6cc)
It does have the same issue.
I think [requesting some peripherals](https://github.com/SuperSpaceEye/Some-Peripherals/issues/17) to add a blacklist feature is a solution.

**Comment by rbasamoyai** [comment]
Will close this then, I do not feel like this is a Create Big Cannons issue for any mods that are affected by raycasts like this.
