### ISSUE TITLE
[Fabric] Incompatible with FarmersDelight-Refabricated

### ISSUE THREAD

**Issue by ERroooooR** [Cannoneers-of-Create/CreateBigCannons#483]
log：https://mclo.gs/fXVmfGI
FarmersDelight-Refabricated：https://github.com/MehVahdJukaar/FarmersDelight

**Comment by rbasamoyai** [comment]
Create Big Cannons is not yet updated for Create 0.5.1.f on Fabric yet.

**Comment by rbasamoyai** [comment]
Fixed in latest indev version and will be closed on next release.
