### ISSUE TITLE
Suggestion: customizable shells

### ISSUE THREAD

**Issue by Pampararararam** [Cannoneers-of-Create/CreateBigCannons#485]
HE shell is too weak and dont have base detonator so I cant use it on quick breech cannon. Tried to do something in jar file and all i have done is to change explosion power and break the he shell by setting "base_fuse" to true. It would be really cool if a customizable shell added or some instructions on customizing/adding shells are made. Hope i wrote it correctly.

**Comment by rbasamoyai** [comment]
You have to make your own addon. KubeJS support or other pack-driven-like solutions are currently not being pursued.
