### ISSUE TITLE
incompatibility with create interactive

### ISSUE THREAD

**Issue by Pampararararam** [Cannoneers-of-Create/CreateBigCannons#486]
![2024-03-30_02 38 33](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/73831400/ccd01d2a-b689-4a72-9877-8228a6307f7d)
![2024-03-30_02 38 40](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/73831400/165c8726-3ab4-43e0-ba77-5772ca24934a)
![2024-03-30_02 38 43](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/73831400/86a577a9-4b4b-4522-87d7-0fbf9d6ee54f)
doesnot render world while sitting at machine gun

**Comment by rbasamoyai** [comment]
A Create Interactive issue, unfortunately. Please report this to the Create Interactive developers.
