### ISSUE TITLE
When I run the client in IntelliJ IDEA I get the mixin error

### ISSUE THREAD

**Issue by shuangfas** [Cannoneers-of-Create/CreateBigCannons#487]
I put cbc as a dependency on my mod,I runClient,but get a mixin error!
my gradle dependencies
***
    minecraft 'net.minecraftforge:forge:1.18.2-40.2.17'

    implementation fg.deobf("com.simibubi.create:create-${mc_version}:${create_version}:slim") { transitive = false }
    implementation fg.deobf("com.jozufozu.flywheel:flywheel-forge-${mc_version}:${flywheel_version}")
    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")

    implementation fg.deobf("com.rbasamoyai:ritchiesprojectilelib:1.0.0-e3f8fa2+1.18.2-forge") { transitive = false }

    implementation fg.deobf("com.rbasamoyai:createbigcannons-forge-${mc_version}:0.5.4-nightly-2697705")

    implementation fg.deobf("org.squiddev:cc-tweaked-${mc_version}:${cct_version}")
***
log
[debug.log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/14812337/debug.log)

**Comment by realRobotix** [comment]
We generally suggest using Architectury Loom with the same mappings as cbc to build addons.
I'm not too familiar with fg but you could check if cbc is properly remapped and the method is included in the mappings you're using. use [this](https://github.com/minMaximilian/maxs-pvp-enhancements/blob/1.19/release/forge/build.gradle) as a refrence

**Comment by realRobotix** [comment]
This seems to be a known issue with FG3 and later: https://docs.architectury.dev/loom/fg_mixin_refmaps

**Comment by shuangfas** [comment]
I read https://github.com/SpongePowered/Mixin/issues/462
and solved my problem, thank you!
