### ISSUE TITLE
Autocannon handle on VS structures works wrongly

### ISSUE THREAD

**Issue by mlgmdd** [Cannoneers-of-Create/CreateBigCannons#514]
Player in a wrong place when using the autocannon's handle on Valkyrien Skies structures
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/109269794/7487870a-2c6a-488c-847f-2e9ce1a54a4f)
![2024-04-06_01 02 38](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/109269794/a54bcd98-4e65-49f8-acb2-4da165295039)
![2024-04-06_01 03 06](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/109269794/d1319d0f-fe07-4053-a75b-984503e2de05)
![2024-04-06_01 03 49](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/109269794/113bfe54-a374-4496-bc17-061fd0f701c9)

Game version: 1.18.2
Forge: 40.2.18
Valkyrien Skies: 2.1.1-beta.6+b1ee932637

**Comment by rbasamoyai** [comment]
This is a Valkyrien Skies issue. Please take it up with them.
