### ISSUE TITLE
[1.18.2] Crashes when assembling Create Big Cannons autocannon

### ISSUE THREAD

**Issue by TqLxQuanZ** [Cannoneers-of-Create/CreateBigCannons#515]
Mod Version: 1.18.2 - 0.2.1 - https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat/files/4631182
CreateBigCannons Version: 1.18.2-0.5.3.b
Create Version: create-1.18.2-0.5.1.f

Apparently, whenever you're trying to assemble the autocannon using cannon mount. The moment you pull down the lever to assemble them, the game crashes.
It does not crash if played without flywheel compact.

Unfortunately, regarding the log it doesn't show any good information, it is something related to straight up crashing the game without logging out the crash issue.
[latest.log](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/14892748/latest.log)

Here's a video recording it, hope it'll be helpful.
https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/31058251/c9eaf916-d91d-4b93-8e59-c8c3309014fe

**Comment by TqLxQuanZ** [comment]
Apologies on the previous ticket, forgot to follow up, been quite busy recently.

**Comment by rbasamoyai** [comment]
Could you send a mod list? Also, do you have a crash report, and is this on a server?

**Comment by TqLxQuanZ** [comment]
There is no crash report generated, however I found out some new info.
Switching flywheel backend to "instancing" seems to work properly, just "batching" has issue.

The modlist is quite large, mod pack came from https://www.curseforge.com/minecraft/modpacks/deceasedcraft

Modlists:
https://legacy.curseforge.com/minecraft/modpacks/deceasedcraft/relations/dependencies

Tested on single-player, not on server.

**Comment by rbasamoyai** [comment]
Does backend off work?

**Comment by TqLxQuanZ** [comment]
Yup, backend off works as well.

**Comment by rbasamoyai** [comment]
Tried this in a bare installation with CBC and Create (read: dev env) and it works fine. I suspect it's an issue with one of the mods you have.
I mainly suspect Canary, but there seems to be a few other performance mods in your pack as well. If you could try some of those perfmods together with CBC that'd be great, but I could try your pack later.

**Comment by TqLxQuanZ** [comment]
My apologies, after narrowing down the optimization mods, it seems to be Embeddium/Oculus having issue with Create/OculusFlywheelCompat, doesn't seem to be related with create big cannons, I'll transfer this issue to Embeddium's github.
