### ISSUE TITLE
[SUGGESTION] Make tooltips for Cannon Blocks less ugly

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#52]
Solution: Add extra spaces with • (type alt+7 on your keytab)  symbol for cannon tooltips to prevent misunderstandings.
sorry for using russian instead english, i'm currently doing major rework with localization

**Without** 🤢🤢🤢:
![2022-07-30_17 06 35](https://user-images.githubusercontent.com/109973204/181921126-5bd3014c-f98a-4078-b22a-dd8e8adab6e2.png)

**With Spaces** 😃😃😃:
![2022-07-30_16 47 52](https://user-images.githubusercontent.com/109973204/181921137-e69446bb-d693-4c22-b65b-ff41d349db2b.png)

**With Spaces and Unicode • Symbol** 😎😎😎:
![2022-07-30_17 04 13](https://user-images.githubusercontent.com/109973204/181921140-a6f0285a-1c2e-41d5-a89b-45d01d0c67bd.png)

**Comment by rbasamoyai** [comment]
Implemented in https://github.com/rbasamoyai/CreateBigCannons/commit/6f0faf741c6e43d3dbb678fc7bde6860b49ba760
