### ISSUE TITLE
Crashing on 1.20.1 (0.15.7) Fabric 0.5.3.b

### ISSUE THREAD

**Issue by hugo3125** [Cannoneers-of-Create/CreateBigCannons#521]
tried on other versions: 0.5.3.b, 0.5.3.a, 0.5.3, 0.5.2.a
[log.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/14950774/log.txt)
Thanks for any response 👍

**Comment by rbasamoyai** [comment]
Use the latest Github nightly.
