### ISSUE TITLE
a bug with create[1.20.1][0.5.3b]

### ISSUE THREAD

**Issue by kingniu4** [Cannoneers-of-Create/CreateBigCannons#528]
Use createbigconnons's Pouring bug to replace blaze burner,which get access to endless energy

**Comment by rbasamoyai** [comment]
Could you send a video of this?

**Comment by rbasamoyai** [comment]
Checking back again: @kingniu4 do you have a video of this issue occuring?

**Comment by rbasamoyai** [comment]
Bump

**Comment by kingniu4** [comment]
sorry, I test it. This bug only require [create] mod

**Comment by rbasamoyai** [comment]
Okay, can you send a video?

**Comment by rbasamoyai** [comment]
Is it in any way related to Create Big Cannons?

**Comment by kingniu4** [comment]
no relation, just create bug , sorry  T^T

**Comment by kingniu4** [comment]
Uploading create-bug-1.mp4…

**Comment by kingniu4** [comment]
https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/98977392/7be54ae7-b8f0-4d5a-8c92-5f25639fc095
