### ISSUE TITLE
Artillery shells bypass region protection both FTB chunks and worldguard.

### ISSUE THREAD

**Issue by JeeNearAll** [Cannoneers-of-Create/CreateBigCannons#529]
Cannons can pierce through blocks in the protected regions ignoring (all) most of the tested settings both on local and conventional server. Yet explosion damage is blocked
![2024-04-15_18-01-43](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/103207789/8865a7fd-cd1f-4fd5-81f4-d3f5a5ec5021)

**Comment by rbasamoyai** [comment]
Bump. I am of the opinion that world protection mods should probably handle this themselves; there are probably a few such mods and having to establish compat with them feels like odd code design.

To elaborate on this: Create Big Cannons does not use fake players actors to destroy blocks, compared to Create. I do not think that fake players are warranted for projectile destruction.

Will close this issue as **Not planned.**
