### ISSUE TITLE
[fabric 1.20.1] unexpected crash

### ISSUE THREAD

**Issue by neotrit** [Cannoneers-of-Create/CreateBigCannons#534]
crashing on create version 0.5.1f

**Comment by ydedwq1** [comment]
Where did you get this version?

**Comment by neotrit** [comment]
version of create?
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/127990510/d0fd6275-fa98-4c1c-a7b3-288e34da5495)

**Comment by rbasamoyai** [comment]
Most fabric issues have been fixed on the latest indev builds, will be in next release
