### ISSUE TITLE
Put the fact bronze and steel are dependent on other mods in the mod descriptions on CF and update it on modrinth pls

### ISSUE THREAD

**Issue by FatherSarge** [Cannoneers-of-Create/CreateBigCannons#535]
Create: Alloyed isn't up to date, ingotcraft is however
https://www.curseforge.com/minecraft/mc-mods/ingotcraft

This isn't really expressed on the curseforge page unfortunately. Might stop some confusion

**Comment by rbasamoyai** [comment]
Updated.
