### ISSUE TITLE
Impact fuze with quick-firing breech

### ISSUE THREAD

**Issue by gegentan** [Cannoneers-of-Create/CreateBigCannons#539]
When I insert a HE shell into a cannon through a quick-firing breech, I am unable to apply the impact fuze to the HE shell. This makes the cannon fire a "dummy" (not exploding) shell.

**Comment by rbasamoyai** [comment]
Add the fuze before hand and break the block. The dropped item will have the fuze.

**Comment by gegentan** [comment]
You mean place the HE shell, add the fuze and break the HE shell?
