### ISSUE TITLE
ram and worm head doesn't works

### ISSUE THREAD

**Issue by Crystal-guy** [Cannoneers-of-Create/CreateBigCannons#54]
I cant push any  head, with or without the charge.

without the head, i can move the pistons poles, but when i place a head, it dont want to push it.

OS= Windows
version=1.18.2-beta-0.2

![2022-07-30_18 01 56](https://user-images.githubusercontent.com/79054553/181925318-7f5e599b-eb0b-45e6-9375-bf8b2939f995.png)
![2022-07-30_18 02 00](https://user-images.githubusercontent.com/79054553/181925333-cce0ec37-4c65-4365-b0ad-8917e67d419c.png)
![2022-07-30_18 01 03](https://user-images.githubusercontent.com/79054553/181925298-2b957a80-9f45-4718-b0af-7a1cd70411cd.png)
![2022-07-30_18 01 09](https://user-images.githubusercontent.com/79054553/181925305-8801d450-7758-4add-bb98-007850eb7490.png)
![2022-07-30_18 01 21](https://user-images.githubusercontent.com/79054553/181925309-03c52b77-5602-499d-b233-bd2979c6bb1b.png)

**Comment by rbasamoyai** [comment]
beta 0.2 a bit of a buggy mess, try the nightlies while you wait for beta-0.3
