### ISSUE TITLE
Cannon Yaw angle inconsistant

### ISSUE THREAD

**Issue by jam-jar-binks** [Cannoneers-of-Create/CreateBigCannons#544]
When a cannon is rotated the yaw angle will either decrease from 180 or jump  to -180 and increase. This seems so mainly be caused by the cannon being controlled by a player, however I've also seen it just arbitrarily decide to start at different yaw angles for non player controlled cannons.

all cannons are assembled facing north, as is the mount.

![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79160978/c2074358-39f2-47a4-a59a-0bcc28a289bc)
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79160978/60086b21-dca9-407d-8fd3-dd0f29210275)
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/79160978/32ccec57-8298-42b9-ab75-da204a27bb06)

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/b954af088a00ac7112726ca3420ca3d4ebee89a8.
