### ISSUE TITLE
trying to find initial velocity calculations for projectile

### ISSUE THREAD

**Issue by bobberwobber** [Cannoneers-of-Create/CreateBigCannons#550]
trying to calculate where to aim the cannon to hit a certain coordinate, very hard without knowing exact velocity calculations.

**Comment by rbasamoyai** [comment]
The propellant in the mod has a tooltip showing how much velocity it adds to the projectile.

Please note: this is a support board for bugs and enhancements related to the mod, not a help board for how to make things. If you woukd like to learn from community members more about the mod's content and what to do with it, I suggest you join the mod Discord, which can be found on the mod Github/CurseForge/Modrinth page.
