### ISSUE TITLE
5.5.0 crash in forge 1.18.2

### ISSUE THREAD

**Issue by KODU16** [Cannoneers-of-Create/CreateBigCannons#560]
[crash-2024-06-02_16.50.12-client.txt](https://github.com/user-attachments/files/15524718/crash-2024-06-02_16.50.12-client.txt)

**Comment by rbasamoyai** [comment]
Remove Create Big Cannons Modern Warfare. It does not work with the current indev version of Big Cannons and leads to this error "caused"
by Big Cannons.
