### ISSUE TITLE
[Bug] Autocannons not recognized (Potential mod incompatability)

### ISSUE THREAD

**Issue by NeedsterW** [Cannoneers-of-Create/CreateBigCannons#562]
As the title suggests, I'm unable to create autocannons on a personal modpack due to what I'm assuming is the autocannon parts not being recognized (due to the lack of the particles when placed on a Cannon Mount or Cannon Carriage). I have not tested this with Create and CBC only, so for the moment I'm assuming it's an incompatibility with some mod(s) in my modpack.
[EDIT: It very well could be that I'm assembling it incorrectly, however I'm not fully sure]
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/136638877/994edd53-25bd-4892-a45a-21dd3e09e629)
![image](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/136638877/60311b3a-2b5c-4260-b8c9-07fdbd0a832a)

**Comment by NeedsterW** [comment]
Update: I made sure all parts were facing the same direction, and it still did not work, however it did work on a modpack with just Create and this addon, so it's almost certainly something with mod incompatibilities

**Comment by rbasamoyai** [comment]
Could you send your mod list?

**Comment by NeedsterW** [comment]
> Could you send your mod list?
It's a bit long seeing as I copied it directly from the latest.log but,
- advancements_tracker 6.1.0
	- alexscaves 1.1.4
	- alexscaves_torpedoes 1.0.2
	- alexscaves_trimmed 1.0.2
	- alexscavesdimension 1.0.0
	- alexsdelight 1.5
	- alexsmobs 1.22.8
	- alexsmobsinteraction 3.1
	- almostunified 1.20.1-0.9.3
	- alternate_current 1.7.0
	- ambientenvironment 11.0.0.1
	- ambientsounds 6.0.1
	- amendments 1.20-1.2.3
	- appleskin 2.5.1+mc1.20.1
	- archaeologybanners 5.1.6
	- architectury 9.2.14
	- armorstatues 8.0.6
	- attributefix 21.0.4
	- automobility 0.4.2+1.20.1-forge
	- badmobs 19.0.2
	- balm 7.3.4
		\-- kuma_api 20.1.6
	- barteringstation 8.0.0
	- beachparty 1.1.5
	- bedspreads 6.2.0+1.20.1
	- bellsandwhistles 0.4.3-1.20.x
	- betterarcheology 1.1.9-1.20.1
	- betterburning 9.0.2
	- betterchunkloading 1.20.1-4.3
	- betterfoliage 5.0.2
	- betterfpsdist 1.20.1-4.4
	- betterinvisibility 1.0.4
	- betterthirdperson 1.9.0
	- bettertridents 8.0.1
	- blueflame 1.20.0-1.0.3
	- blueprint 7.1.0
	- boatbreakfix 1.0.2
	- bocchium 1.20.1-0.0.3
	- bookshelf 20.1.11
	- bwncr 3.17.0
	- caelus 3.2.0+1.20.1
	- canary 0.3.3
	- cccbridge 1.6.3-forge
	- cgm 1.4.17
	- chimes 2.0.1
	- chunksending 1.20.1-2.8
	- citadel 2.5.4
	- citresewn 1.20.1-5
	- clickadv 1.20.1-3.8
	- clientcrafting 1.20.1-1.8
	- clienttweaks 11.1.0
	- cloth_config 11.1.118
	- clumps 12.0.0.4
	- collective 7.61
	- computercraft 1.111.0
	- connectiblechains 1.0.0
	- connectivity 1.20.1-5.5
	- controlling 12.0.2
	- copperandtuffbackport 1.2
	- coroutil 1.20.1-1.3.7
	- cpm 0.6.17a
	- cpmsvcc 1.2.1
	- crabbersdelight 1.1.4
	- create 0.5.1.f
		\-- flywheel 0.6.10-7
	- create_central_kitchen 1.3.12
		\-- create_dragon_lib 1.4.3
	- create_confectionery 1.1.0
	- create_connected 0.8.2-mc1.20.1
	- create_enchantment_industry 1.2.9.d
	- create_oppenheimered 1.0.2
	- create_quark_runes 1.0.0
	- create_sa 2.0.4.
	- create_tweaked_controllers 1.20.1-1.2.4
	- createaddition 1.20.1-1.2.3
	- createaddoncompatibility 0.2.0
	- createbigcannons 0.5.4-nightly-8b9cea6
		\-- ritchiesprojectilelib 1.0.0-369e88d+1.20.1-forge
	- createcafe 1.2.4-1.20.1
	- createdeco 2.0.2-1.20.1-forge
	- createrailwaysnavigator 0.5.3-beta-1.20.1-forge
		\-- dragonlib 1.20.1-2.1.8
	- creativecore 2.11.30
	- creeper_firework 2.1.0.b
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.6
	- curios 5.9.1+1.20.1
	- cutthrough 8.0.2
	- davebuildingmod 5.0
	- decorative_blocks 4.1.3
	- decorative_gaming_consoles 1.1.0
	- delightful 3.5.5
	- design_decor 0.4.0
	- deuf 1.20.1-1.3
	- diagonalfences 8.1.4
	- diagonalwalls 8.0.3
		\-- diagonalblocks 8.0.5
	- diagonalwindows 8.1.4
	- display 1.2.2
	- distanthorizons 2.1.0-a
	- doapi 1.2.12
		\-- terraform 7.0.1
	- doespotatotick 1.20.1-4.0.2
	- dolphin_fix 1.0.0
	- domesticationinnovation 1.7.1
	- dummmmmmy 1.20-1.8.17b
	- dye_depot 1.20.1-1.0.0
	- dynamiclightsreforged 1.20.1_v1.6.0
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.2
		|-- puzzlesaccessapi 8.0.9
		\-- puzzlesapi 8.1.6
	- ecologics 2.2.0
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.19+mc1.20.1
		\-- rubidium 0.7.1
	- enchdesc 17.0.16
	- enemyexpansion 2.3.1
	- entity_model_features 2.0.2
	- entity_texture_features 6.0.1
	- entityculling 1.6.5
	- essential 1.3.2.5+ge4fdbcd438
	- farmersdelight 1.20.1-1.2.4
	- farsight_view 1.20.1-3.6
	- fastload 3.4.0
	- fastpaintings 1.20-1.2.7
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- forge 47.2.20
	- fps_increaser 1.0.0
	- fpsreducer 1.20-2.5
	- framework 0.7.6
	- ftbchunks 2001.3.1
	- ftblibrary 2001.2.2
	- ftbteams 2001.3.0
	- geckolib 4.4.5
	- gpumemleakfix 1.20.1-1.8
	- grindless_pottery_shards 1.0.0
	- guardvillagers 1.20.1-1.6.5
	- gunners 0.0.2
	- heartstone 1.20-1.3.0
	- icterine 1.3.0
	- immediatelyfast 1.2.17+1.20.4
	- immersive_aircraft 1.0.1+1.20.1
	- immersive_melodies 0.2.0+1.20.1
	- immersive_paintings 0.6.7+1.20.1
	- interiors 0.5.3+forge-mc1.20.1
	- irisflw 1.20.1-0.2.5
	- iwannaskate 1.2.0
	- jade 11.9.2+forge
	- jadeaddons 5.2.2
	- jea 1.20.1-5.0.1
	- jearchaeology 1.20.1-1.0.4
	- jeed 1.20-2.1.12
	- jepp 1.20-1.1.2
	- jeresources 1.4.0.247
	- jmi 1.20.1-0.14-45
	- journeymap 5.9.23
	- justabaguette 1.0.0
	- justenoughbreeding 1.2.1
	- kotlinforforge 4.10.0
	- kubejs 2001.6.5-build.7
	- kubejs_create 2001.2.5-build.2
	- leaky 1.20.1-2.1
	- leap 1.1.2
	- libreexpfix 0.2.7b14-BETA
	- libx 1.20.1-5.0.12
	- lootr 0.7.34.85
	- loud_horns 1.0.2
	- make_bubbles_pop 0.2.0-forge
	- maxhealthfix 12.0.3
	- mcwbridges 3.0.0
	- mighty_mail 1.0.14
	- minecraft 1.20.1
	- mining_dimension 1.20.1-1.1.0
	- mobtimizations 1.20.1-1.0.0
	- moderately_enough_effect_desc 3.3.0
	- modernfix 5.18.0+mc1.20.1
	- molten_metals 1.20.1-0.1.4
	- moonlight 1.20-2.11.31
	- mousetweaks 2.25.1
	- moyai 1.20-2.1.4
	- mysticaloaktree 1.20-1.11
	- necronomicon 1.4.2
	- needsters_music_discs 1.0.0
	- netherportalfix 13.0.1
	- nocubes_craftable_armor_trims 1.0.0
	- nocubes_craftable_md 0.9
	- notenoughanimations 1.7.3
	- notenoughcrashes 4.4.7+1.20.1
	- numismatics 1.0.6+forge-mc1.20.1
	- oculus 1.7.0
	- paintings_backport 1.0.0
	- pehkui 3.8.2+1.20.1-forge
		\-- mixinextras 0.3.6
	- placebo 8.6.1
	- plentyplates 8.0.0
	- polymorph 0.49.5+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- purediscstrickytrials 1.0.0
	- puzzleslib 8.1.20
	- quark 4.0-455
	- quarkdelight 1.0.0
	- railways 1.6.4+forge-mc1.20.1
	- rare_ice 0.0NONE
	- rei_plugin_compatibilities 12.0.93
		\-- jei 15.9999
	- rhino 2001.2.2-build.18
	- roughlyenoughitems 12.1.725
	- saturn 0.1.3
	- scholar 1.0.0
	- searchables 1.0.3
	- sleep_tight 1.20-1.1.19
	- sleep_time 1.20.1
	- sliceanddice 3.2.0
	- smoothboot 0.0.4
	- snowyspirit 1.20-3.0.6
	- sophisticatedbackpacks 3.20.5.1044
	- sophisticatedcore 0.6.22.611
	- sound_physics_remastered 1.20.1-1.4.2
	- spark 1.10.53
	- starlight 1.1.2+forge.1cda73c
	- strawstatues 8.0.3
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.11
		\-- mixinsquared 0.1.1
	- suppsquared 1.20-1.1.14
	- swordblockingmechanics 8.0.1
	- tact 1.1.5
	- temporalapi 1.6.2
	- tiltbreak 1.20.1-1.4FE
	- toastcontrol 8.0.3
	- trade_cycling 1.20.1-1.0.7
	- universalbonemeal 8.0.1
	- universalenchants 8.0.0
	- upgrade_aquatic 6.0.0
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- voicechat 1.20.1-2.5.15
	- waveycapes 1.4.7
	- whatthebucket 11.0.3
	- wither_drops_netherite_templates 1.0.0
	- wormhole 1.1.16
	- yungsapi 1.20-Forge-4.0.5
	- zeta 1.0-16

**Comment by rbasamoyai** [comment]
Do you have any game logs with this issue recorded?

**Comment by rbasamoyai** [comment]
Actually, looking at your cannon now, did you assemble the autocannon in survival, piece by piece, by hand? If so, you must use the cannon welder to assemble it. It is recommended you cast your cannons whole instead.

**Comment by NeedsterW** [comment]
> Actually, looking at your cannon now, did you assemble the autocannon in survival, piece by piece, by hand? If so, you must use the cannon welder to assemble it. It is recommended you cast your cannons whole instead.

Yes, I did assemble it by hand, thanks for clarifying!
