### ISSUE TITLE
I can't get the cannon loader to move.

### ISSUE THREAD

**Issue by John-Adler** [Cannoneers-of-Create/CreateBigCannons#57]
My cannon loader won't move when I try to load my cannon, except in rare circumstances. I'm not sure why. Am I doing something wrong? I haven't found a reason online. Please fix.

**Comment by rbasamoyai** [comment]
Make sure your cannon loader is oriented the right way - the head should be connected to the little piston pole sticking out of the loader.

I am aware that this is a common failing, so I might consider making the cannon loader a bit less confusing.
