### ISSUE TITLE
How to adjust autocannon spread and damage?

### ISSUE THREAD

**Issue by Nycto4bia** [Cannoneers-of-Create/CreateBigCannons#573]
Having assembled the longest autocannon, I wasn't satisfied with its accuracy. I would also like to increase the damage, but I didn't find any options in the settings.

**Comment by rbasamoyai** [comment]
Use datapacks.
How to make and format a data pack: https://minecraft.wiki/w/Data_pack
Autocannon material format: https://github.com/Cannoneers-of-Create/CreateBigCannons/blob/1.18.2/dev/common/src/main/resources/data/example_createbigcannons/autocannon_materials/example.json
(in-game materials: `createbigcannons:cast_iron`, `createbigcannons:bronze`, `createbigcannons:steel`)
Autocannon projectiles: https://github.com/Cannoneers-of-Create/CreateBigCannons/tree/1.18.2/dev/common/src/main/resources/data/createbigcannons/munition_properties/projectiles
(`flak_autocannon`, `ap_autocannon`, `machine_gun_bullet`)

**Comment by Nycto4bia** [comment]
> Use datapacks. How to make and format a data pack: https://minecraft.wiki/w/Data_pack Autocannon material format: https://github.com/Cannoneers-of-Create/CreateBigCannons/blob/1.18.2/dev/common/src/main/resources/data/example_createbigcannons/autocannon_materials/example.json (in-game materials: `createbigcannons:cast_iron`, `createbigcannons:bronze`, `createbigcannons:steel`) Autocannon projectiles: https://github.com/Cannoneers-of-Create/CreateBigCannons/tree/1.18.2/dev/common/src/main/resources/data/createbigcannons/munition_properties/projectiles (`flak_autocannon`, `ap_autocannon`, `machine_gun_bullet`)

If it's not too much trouble, could you explain it to the dumb? This is the first time I create a datapack. 
I still don't understand what the path, folder and file names should be, since the autocannon is a structure of several blocks.
I did: _datapack/bigcannonsetting.zip/data and pack.mcmeta/create_big_cannons/autocannon_materials/autocannon.json (example.json)_
The datapack is readable by the world, but the edited settings do not change.
