### ISSUE TITLE
Cant play any world

### ISSUE THREAD

**Issue by hoklm981** [Cannoneers-of-Create/CreateBigCannons#575]
i got this problem when i was joining my singleplayer world or joining my friends essential server.
![屏幕截图 2024-06-26 161250](https://github.com/Cannoneers-of-Create/CreateBigCannons/assets/173888642/26fec4b4-a3c7-4f0a-a5d1-de47726b2537)

**Comment by rbasamoyai** [comment]
Update Create to 0.5.1.f _patch 1_ if you are using 0.5.4
