### ISSUE TITLE
breechloader now doesn't work cause the whole cannon moves together when pulled by the plunger

### ISSUE THREAD

**Issue by kamitojaeger** [Cannoneers-of-Create/CreateBigCannons#58]
change the mod's version from  **[createbigcannons-1.18.2-beta-0.2]**  to  **[e.g. nightly-4b2bde7 / beta-0.1]** 
and i found that i **can't load the cannon from the breech** 

when i use plunger to pull the breech and the end from the side
**the barrel and the chamber moves together** 
so there's no way to load the cannon from the breech

this issue is not founded when using  [createbigcannons-1.18.2-beta-0.2]

![Minecraft_ 1 18 2 - 单人游戏 2022_7_31 13_53_30](https://user-images.githubusercontent.com/110318836/182012901-877792f7-e8aa-4e05-afc0-48baff655abc.png)

![Minecraft_ 1 18 2 - 单人游戏 2022_7_31 13_53_37](https://user-images.githubusercontent.com/110318836/182012861-a095f26d-ff15-472a-bae5-3ce08e9e26c7.png)

**Comment by Crabanutij** [comment]
Firstly, you don't have to use glue. To push screw breech, you unscrew it, and then push it away. You also don't have to use two different breeches at the same time.
