### ISSUE TITLE
Shell chunk loading failed bug

### ISSUE THREAD

**Issue by kamitojaeger** [Cannoneers-of-Create/CreateBigCannons#586]
Shells can load chunks so that it can hit target chunks away.
I found an exception :

In single player game, when fire at a target that's chunks away, there are 2 kinds of chunks the shell will go through after firing the cannon

1. Cannon Chunks -- where the cannon is at, needs player or chunk loader to load so that the cannon can be fired
2. Target chunks & Chunks between Cannon and targets, I will called them as one "Target Chunks"

In normal condition, after the shell leaves the "Cannon chunks" where player is at, it will begin to load the "Target Chunks".

But, 
BEFORE the shell leaves the "Cannon Chunks", if player transport itself to other places, making "Cannon Chunks" unloaded, then the shell would also be unloaded, it can not load the chunks and fly to its target no more

To test this issue, you can follow these steps below:

1. Set up a big cannon that's capable of firing at targets beyond chunk loading
2. Do a test fire and mark the position where the shell falls
3. Go back to the cannon, fire the cannon and rapidly transport yourself to the position you had marked right after you fire it. (like within 1 sec)
4. Check if the shell falls (the shell might not fall)
5. Transport back to the cannon, fire the cannon, and transport yourself to the position you had marked after you see the smoke trail of the shell has completely fade away
6. check if the shell falls (the shell should fall, and there is possibility that the shell you fired in step 3 also falls down with the new shell you had just fired.)
7. if there's only 1 shell falls down, fly back to the cannon, check if the shell you fired in step 3 shows up during the way you fly back

I can send you the video I test this issue with Email.

![GD6D_CO(~QSNTODX66)@_FX](https://github.com/user-attachments/assets/bd2aec4f-92d7-4578-b222-4d2e1b9f113d)

**Comment by kamitojaeger** [comment]
https://drive.google.com/file/d/1tVB4yd9nYNgPSPAl5NH5U1p_yd5a5nZ8/view?usp=sharing

here's the video

**Comment by rbasamoyai** [comment]
Could just try queueing forceload for the projectile on firing, will try this later

**Comment by rbasamoyai** [comment]
I see that you're doing this with modern warfare. Could you try this with vanilla Big Cannons?

**Comment by kamitojaeger** [comment]
> I see that you're doing this with modern warfare. Could you try this with vanilla Big Cannons?

https://drive.google.com/file/d/1a4pDA0g9E7njioDrwkYmpxHmo3XLIXqE/view?usp=sharing
yes, this issue can be reproduce with vanilla big cannons

**Comment by rbasamoyai** [comment]
Did you enable projectile chunkloading? Have you edited the Ritchie's Projectile Lib chunkloading config?

**Comment by kamitojaeger** [comment]
> Did you enable projectile chunkloading? Have you edited the Ritchie's Projectile Lib chunkloading config?

![image](https://github.com/user-attachments/assets/5217a462-c219-4b79-9f4b-3790517ff8a4)
I had never edited the config of Ritchie's Projectile Lib chunkloading

**Comment by rbasamoyai** [comment]
Can reproduce this issue, investigating it

**Comment by rbasamoyai** [comment]
Should be fixed-ish in dev - chunks will not start ticking down their age in earnest until they have entities loaded, or until the entity loading timeout is exceeded. The timeout will be configurable through the Ritchie's Projectile Library config. Wait for the latest nightly to try the fix out - I will reply back with a link to a PR for this fix.

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/587.
