### ISSUE TITLE
minecraft crashes when using nightly

### ISSUE THREAD

**Issue by uglyfulk** [Cannoneers-of-Create/CreateBigCannons#59]
**Describe the bug**
Minecraft crashes when using "createbigcannons-1.18.2-nightly-abc2287"
![image_2022-07-31_180946119](https://user-images.githubusercontent.com/110327857/182016471-16713f61-72da-4c11-a4f1-aa92b23b8033.png)

mods used are 
-create
-create big cannons
-flywheel

**Comment by rbasamoyai** [comment]
Crash report?
