### ISSUE TITLE
AutoCannon lacks fire sound on ValkyrienSky Ship

### ISSUE THREAD

**Issue by CryJoyYarn** [Cannoneers-of-Create/CreateBigCannons#596]
Forge 1.18.2 (40.2.21), CBC 5.5.0 build34
ValkyrienSky 2.1.1 beta5
Autocannon(and Machinegun) on ground has fire sound, but on VS ship it doesn't. Bigcannon's fire sound works fine on both ground and VS ship.
This problem doesn't exist on CBC5.4.0
![2024-07-17_15 04 06](https://github.com/user-attachments/assets/4521d62a-96b8-462a-a19c-1060f47acd7c)

![2024-07-17_15 03 57](https://github.com/user-attachments/assets/fddfb7f3-fe44-47b7-9c8a-e4bf6fe90a42)

**Comment by rbasamoyai** [comment]
![image](https://github.com/user-attachments/assets/9d08849f-2084-4e81-9e8e-0db4ec2c064d)

The issue can be fixed here, however I believe this is an issue to be resolved by the Valkyrien Skies mod.

**Comment by rbasamoyai** [comment]
@ThePlasticPotato if you'd like to fix this in VS2 when CBC 5.5.0 is released...
