### ISSUE TITLE
Other shells eg. sharpnel or HE don't seem to change anything even with fuse

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#6]
the HE and shrapnel shells exploded just like solid shots even if the he one had a fuse

**Comment by rbasamoyai** [comment]
Footage?

**Comment by Abrams11IsBack** [comment]
> Footage?

it seems to work without the fuse but just when the fuse is applied there is no damage

**Comment by Abrams11IsBack** [comment]
![obraz](https://user-images.githubusercontent.com/71346253/180559850-9439fd8d-acd4-43dc-84f5-324f036e8947.png)

damage without the fuse

**Comment by Abrams11IsBack** [comment]
with the fuse the damage was roughly 1 block (where the projectile hit)

**Comment by Abrams11IsBack** [comment]
weird because on my friends world the impact fuze worked

**Comment by Abrams11IsBack** [comment]
i need to test more

**Comment by rbasamoyai** [comment]
check the thing in showcase I told you, iirc I made the impact fuze to only detonate after fully breaking through (also, this isn't discord, try to keep your messages together, thanks)
