### ISSUE TITLE
Cannon barrels collision is reversed

### ISSUE THREAD

**Issue by Query74** [Cannoneers-of-Create/CreateBigCannons#62]
**Describe the bug**
When a cannon using the Cannon Barrels is assembled, the barrel's hitbox for player collision is reversed to the other side of the cannon. This does not seem to happen with the wider cannon pieces.

 - OS: Windows
 - Version: createbigcannons-1.18.2-beta-0.2.jar

**To Reproduce**
1. build a cannon using the skinny Cannon Barrel blocks
2. assemble it
3. try to walk on the visible barrel
4. see bug

**Expected behavior**
I expected to be able to walk on the visible cannon barrel like with the wider cannon blocks, and to be able to pass through the visible other side of the cannon with no blocks there.

**Screenshots**
![cannon bug](https://user-images.githubusercontent.com/110355659/182045264-af3762b3-e073-444a-9272-e222cdea8636.png)

**Comment by rbasamoyai** [comment]
Should have been fixed here: https://github.com/rbasamoyai/CreateBigCannons/commit/e21eab8cd084a1b97b3de6e60d55eb2f9b9d6fb0
