### ISSUE TITLE
Can't penetrate VS ship after rotate it

### ISSUE THREAD

**Issue by CryJoyYarn** [Cannoneers-of-Create/CreateBigCannons#628]
1.18.2 CBC 5.5.1/5.5.0 not 5.4.0
Rotate a VS ship by any direction as long as its "default face" is not faced to cannon, then the ship is indestructible.
Plz don't make this another VS2 issue :)
I don't report to VS2 bcz there had been no update for 1.18.2 for almost a year, which means it is highly likely that this bug will NOT be fixed by VS. I really love new sounds and effects on 5.5.0, but due to these bugs I have to use 5.4.0 instead. If other bugs were too difficult to fix, please get this deadly bug fixed if possible, thank you!
![2024-07-26_13 09 33](https://github.com/user-attachments/assets/3c0910dd-b35c-45ea-a8b3-5c471bfde210)
![2024-07-26_13 09 40](https://github.com/user-attachments/assets/ff15b85b-e548-40ea-aa7d-92e8d2cd3623)
<img width="1280" alt="2024-07-26_13 10 20" src="https://github.com/user-attachments/assets/9b0e4833-504e-4deb-8896-1468b44ee7ca">
<img width="1280" alt="2024-07-26_13 10 27" src="https://github.com/user-attachments/assets/1159cbd7-b0a3-4092-ac53-2c127ea053be">

**Comment by rbasamoyai** [comment]
This is still a VS issue. The VS ecosystem should be responsible for catching up with compatibility with this mod.

**Comment by rbasamoyai** [comment]
To elaborate: this is working by design. Create Big Cannons 5.5.0 introduced the effect of impact angle on block breaking, which is calculated via surface normals. By turning the cube 90 degrees without VS having the code to transform the normal (there is a method to mixin for this!) the momentum incident to the actual surface effectively becomes 0.

So, VS should implement the hook.

**Comment by CryJoyYarn** [comment]
Can you add an option to disable this calculation?

**Comment by rbasamoyai** [comment]
I will not, but I may submit a PR (or at least a suggestion) to the VS github to fix this

**Comment by CryJoyYarn** [comment]
Thx anyway
