### ISSUE TITLE
Game crashes at Startup

### ISSUE THREAD

**Issue by ZimmyUwU** [Cannoneers-of-Create/CreateBigCannons#629]
I have a Modpack with a few mods and with the newest version 5.5.0 the game crashes at the startup.

![Bild_2024-07-26_161721747](https://github.com/user-attachments/assets/4afb4666-9036-4ea4-969f-fc235889a026)
[crash-2024-07-26_16.12.51-client.txt](https://github.com/user-attachments/files/16392984/crash-2024-07-26_16.12.51-client.txt)

**Comment by rbasamoyai** [comment]
Install Trinkets for now, this will be fixed in the next release
