### ISSUE TITLE
rotation locks

### ISSUE THREAD

**Issue by robster20022002** [Cannoneers-of-Create/CreateBigCannons#63]
Some kind of system that would prevent a cannon from going past a certain rotation.
Some proposals for implementation:
Using the wrench on the base and yaw controller to limit the angles it can fire.
A block that gets the angle of a shafts rotation and can be set to output a redstone signal if it is greater than, less than or equal to a certain angle. (could be used with the display link to show angles which could be more helpful for aiming artillery as suggested in another post)

![2022-08-03_19 23 38](https://user-images.githubusercontent.com/103005832/182682264-0c558126-be58-44a3-82bf-0ed9aeed59b6.png)

For example. I am looking at making a ship battle game, but I want the cannons to only be able to turn slightly and not aim past those wood planks

**Comment by kiVts** [comment]
You can actually probably do it vanilla style - with redstone contact actually. basically rotation motor, which is passed through clutch and gearshift connected through redstone link. on the other side of gearbox there is a bearing which rotates redstone contact and when it hits "gimbal limit" it sends link signal to the clutch. clutch should be connected through XOR gate in order for it to be able unlock the clutch when you switch direction. in theory should work. also probably you will need to move the gimbal limit back to the center after you disassemble the cannon. this is actually pretty simple.
