### ISSUE TITLE
Big cannons with a problem for the copycat 

### ISSUE THREAD

**Issue by SpartanExtreme** [Cannoneers-of-Create/CreateBigCannons#631]
im getting a crash on initialization , please help, love your mod

[crash-2024-07-28_14.11.36-fml.txt](https://github.com/user-attachments/files/16404627/crash-2024-07-28_14.11.36-fml.txt)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Create Big Cannons (createbigcannons), Version: 5.5.0+mc.1.20.1-forge
		Issue tracker URL: https://github.com/Cannoneers-of-Create/CreateBigCannons/issues
		at TRANSFORMER/createbigcannons@5.5.0+mc.1.20.1-forge/rbasamoyai.createbigcannons.compat.framedblocks.FramedBlocksCompat.init(FramedBlocksCompat.java:17)
Stacktrace:
	at rbasamoyai.createbigcannons.compat.framedblocks.FramedBlocksCompat.init(FramedBlocksCompat.java:17) ~[createbigcannons-5.5.0-mc.1.20.1-forge.jar%23944!/:?] {re:classloading}
-- MOD createbigcannons --
Details:
	Mod File: /C:/Users/Gustavo/AppData/Roaming/.minecraft/mods/createbigcannons-5.5.0-mc.1.20.1-forge.jar
	Failure message: Create Big Cannons (createbigcannons) encountered an error during the common_setup event phase
		java.lang.NoSuchFieldError: FRAMED_ADJ_DOUBLE_COPYCAT_PANEL
	Mod Version: 5.5.0+mc.1.20.1-forge
	Mod Issue URL: https://github.com/Cannoneers-of-Create/CreateBigCannons/issues
	Exception message: java.lang.NoSuchFieldError: FRAMED_ADJ_DOUBLE_COPYCAT_PANEL

**Comment by rbasamoyai** [comment]
This is in fact, not a Copycats problem, but a FramedBlocks problem. To fix this, download FramedBlocks 9.3.0: https://www.curseforge.com/minecraft/mc-mods/framedblocks/files/5399211
