### ISSUE TITLE
Modrinth profile crashing- fabric

### ISSUE THREAD

**Issue by trentTheFirstTiger** [Cannoneers-of-Create/CreateBigCannons#632]
the CreateBigCannons mod crashes when I try to load a modpack with it. 
Here's the client log: https://mclo.gs/T12vvka
And the crash log: https://mclo.gs/lGT9QGK

**Comment by rbasamoyai** [comment]
Install Trinkets as a workaround. This is a known issue that has been fixed in indev, and will be released in 5.5.1, the next CBC release version.

**Comment by trentTheFirstTiger** [comment]
Installing trinkets will allow the profile to launch along with CBC?

**Comment by rbasamoyai** [comment]
yes.
