### ISSUE TITLE
Quick firing breech cannon on a eureka ship can only be fired once, not even rebuilding the cannon allows shooting again

### ISSUE THREAD

**Issue by MCRusher** [Cannoneers-of-Create/CreateBigCannons#636]
Minecraft 1.20.1
Forge 47.3.0
Create 0.5.1.f
Create Big Cannons 5.5.0
Kotlin for Forge 4.11.0
Valkyrien Skies 2 2.3.0.beta.5
VS Eureka Mod 1.5.1-beta.3

After assembling the quick firing cannon, loading it once, and firing; not even destroying all of the cannon including the mount and rebuilding in the same spot will allow the cannon to be loaded again.  Right clicking the breech with a powder charge or shot does nothing and right clicking with an empty hand on the breech just plays the opening animation before setting itself back to closed.

If you build it in another spot on the ship, you get one shot in that spot and then the issue repeats itself.

The other cannons seem to work completely normally.

Very strange.

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/commit/74667f48224c2a3f9b7fdd2dbb5691ae5ecd4db2
