### ISSUE TITLE
Despawning Shells Midair

### ISSUE THREAD

**Issue by therealbabyman** [Cannoneers-of-Create/CreateBigCannons#639]
Shells fired from my nethersteel cannon despawn after about 1.5 seconds facing towards the ground land on terrain and function.
server is 1.20.1
and the version of big cannons is 5.5.0

modlist is as follows:
[modlist.html.pdf](https://github.com/user-attachments/files/16513676/modlist.html.pdf)

if you have any idea on what might be causing it I would appreciate it.

**Comment by rbasamoyai** [comment]
Could you send a video of this behavior?

**Comment by therealbabyman** [comment]
https://www.youtube.com/watch?v=uwapFlMq5Zk

hopefully this is enough.

Cannon firing is at the 3 minute mark.

**Comment by rbasamoyai** [comment]
okay, did you find where the shell landed?

**Comment by rbasamoyai** [comment]
(also, update your CBC version to 5.5.1 if that helps)

**Comment by rbasamoyai** [comment]
in any event, unless if you add a tracer to the shell the shell visually disappears from rendering, but it still should be there

**Comment by therealbabyman** [comment]
shells were still calcuating in the server console. the updating to 5.5.1 works. thanks a bunch!
