### ISSUE TITLE
Armor compability update for copycats slopes?

### ISSUE THREAD

**Issue by CryJoyYarn** [Cannoneers-of-Create/CreateBigCannons#640]
Copycats+ added slopes, doors and other new copycat blocks in recent updates, while cbc hadn't follow up its armor calculation.
Will this be updated?
![2024-08-09_12 04 37](https://github.com/user-attachments/assets/86eb4206-211c-4913-a50c-a94e2da02957)
![2024-08-09_12 04 34](https://github.com/user-attachments/assets/82e2cef9-248f-4a06-9964-3ce0597f5770)
![2024-08-09_12 04 39](https://github.com/user-attachments/assets/5829ed24-78b8-4d78-af71-fe6ebe087f1e)
![2024-08-09_12 04 40](https://github.com/user-attachments/assets/0ac68abc-baf3-4553-ad7f-c8189bece82a)
![2024-08-09_12 05 11](https://github.com/user-attachments/assets/780dad8c-4a40-484f-823f-a630104ed1fa)

**Comment by rbasamoyai** [comment]
Copycats+ tends to be rather unstable, which is why full support for the latest version does not exist yet.
