### ISSUE TITLE
Item pick in creative mode does not preserve the properties of a shell

### ISSUE THREAD

**Issue by Drackonic** [Cannoneers-of-Create/CreateBigCannons#642]
When you item pick (middle click) in creative mode on shells or cartridges it does not keep properties such as the fuze that is attached, what liquid is in a fluid shell, or if a big cartridge has propellant in it. Curiously however it seems that autocannon ammo containers do keep their contents and configuration when item picked.

Minecraft version 1.18.2
Mod Version 5.5.1 Forge

**Comment by rbasamoyai** [comment]
Are you using `ctrl + middle click`?

**Comment by Drackonic** [comment]
> Are you using `ctrl + middle click`?
Could have sworn that did not work when I tried doing that before making the issue but it seems it does now, feel like my game is gaslighting me lol, maybe it was Minecraft itself being strange earlier. My apologies.
