### ISSUE TITLE
Projectiles ignore region protection [further investigation]. Openpac claims, YAWP.

### ISSUE THREAD

**Issue by JeeNearAll** [Cannoneers-of-Create/CreateBigCannons#644]
I am developing the server with your wonderful mod and recently discovered that projectiles completely ignore chunk protection despite the flags that should prevent that (explosions are blocked with no problems). Previously submitted issue was regarding FTB chunks and world protector. Turns out, not even the most popular region protection solutions work. 
Since I might be doing something wrong, I submitted this issue with couple of screenshots showing that flags responsible for block protection are active. 

If thats not an actual issue, could you, please, tell which mods could possibly work in that scenario.
Thank you.

![2024-08-13_22-43-38](https://github.com/user-attachments/assets/c21491c5-fdd5-4c40-a55d-51547d2771b8)
![2024-08-13_22-48-07](https://github.com/user-attachments/assets/1c3fb65e-501c-4cd0-92a6-0d89512fe0e9)
![2024-08-13_22-57-22](https://github.com/user-attachments/assets/51a2703a-c17b-456b-ab33-452ba02939f4)

P.S. Couple of tests was done on the actual server with a non-OP player by shooting protected region with autocannon and dropmortar. Same results

**Comment by JeeNearAll** [comment]
P.P.S. The test presented on the screenshot was done on latest forge version with only create, big cannons and chunk protection mod. So no other mod interfere with the outcome

**Comment by rbasamoyai** [comment]
This is moreso FTB Chunks' thing to do. Not every chunk claim mod can necessarily be covered.

**Comment by JeeNearAll** [comment]
> This is moreso FTB Chunks' thing to do. Not every chunk claim mod can necessarily be covered.

The mod shown is an openpac claims. Literally the most popular solution for chunk protection. From now on, I have no idea which mod works well with big cannons. I submitted similar issue with FTB chunks previously
