### ISSUE TITLE
When used with Valkyrie skies 2 (vs2) bullets faze through vehicles

### ISSUE THREAD

**Issue by ignrpb** [Cannoneers-of-Create/CreateBigCannons#646]
I decided to do a battle where we used eureka mod and vs2 and when I shot a ship but  the projectile just fazed through without damaging but tnt and other create weapons damage the vehicles just fine

**Comment by rbasamoyai** [comment]
This should work with latest Valkyrien Skies and Create Big Cannons; if not, that's likely a VS issue.
