### ISSUE TITLE
1.18.2 Crash Issue

### ISSUE THREAD

**Issue by DevBlox590** [Cannoneers-of-Create/CreateBigCannons#652]
I don't know much about Java code language so here is my crash report. Since it said Create big cannon was "suspected" I post it here
[crash-2024-08-29_11.00.26-fml.txt](https://github.com/user-attachments/files/16796608/crash-2024-08-29_11.00.26-fml.txt)

**Comment by rbasamoyai** [comment]
Send the regular log (in logs) and your mod folder list

**Comment by DevBlox590** [comment]
[2024-08-29-3[1].log](https://github.com/user-attachments/files/16803378/2024-08-29-3.1.log)

**Comment by rbasamoyai** [comment]
You have a broken Tank Tussle pack. This issue will not be supported.
