### ISSUE TITLE
Incompatibe with Eureka

### ISSUE THREAD

**Issue by WorldsOfRosefire** [Cannoneers-of-Create/CreateBigCannons#657]
after assembling the ship with my cannon, also when building a new one on the already assembled ship the cannon is not chargeable, not interactable, it is also flapping up and down when I try to adjust the hight. the jaw controller doesn't seem to work at all. it works fine on the world. the way the ship and cannon assemble seem to interfer.
mc 1.20.1
forge 47.3.5
createbigcannons-5.5.1
create-0.5.1.h
create_connected-0.8.2
clockwork-0.1.16
eureka-1201-1.5.1-beta.3
valkyrienskies-120-2.3.0-beta.5

**Comment by rbasamoyai** [comment]
Create Big Cannons is not yet fully compatible with Create 0.5.1.h. As well, if you could send a video of the issue that would be appreciated.

**Comment by WorldsOfRosefire** [comment]
first you can see it's working fine on default.
next you see how it behaves on the airship, I managed it open it, but can not insert anything. I am also unsing other create addons like connected, dreams n desires where the crank is comming from.

https://cdn.discordapp.com/attachments/1089167214495666206/1283753997001560108/connonbug.mp4?ex=66e42493&is=66e2d313&hm=2077f9007a8b6ad21a2d86c569e4c4b403dd872c610c5e5b8178fda5f8300f0c&

the debug log is spammed with:
[12Sep2024 13:07:38.754] [Netty Local Client IO #0/DEBUG] [org.valkyrienskies.core.impl.networking.NetworkChannel/]: Client received packet of type: PacketType(channel=org.valkyrienskies.core.impl.networking.NetworkChannel@6bfcd804, id=0, name=Ship transform update)
[12Sep2024 13:07:38.787] [Netty Local Client IO #0/DEBUG] [org.valkyrienskies.core.impl.networking.NetworkChannel/]: Client received packet of type: PacketType(channel=org.valkyrienskies.core.impl.networking.NetworkChannel@1ca2b1ad, id=9, name=UDP fallback)

looks like valkyrienskies (eurekas dependency) is forcing the cannon into original possition.

**Comment by rbasamoyai** [comment]
Fixed a while ago, forgot when. Not yet released yet, will close on release

**Comment by WorldsOfRosefire** [comment]
I was testing the newest release. Create 0.5.1.i and createbigcannons-5.6.0-mc.1.20.1-forge. the cannon is still flapping towards original position and I can not load it when build on my eureka ship. opening the quick-fire module is causing that as well.
