### ISSUE TITLE
Crash when loading cannon with ram rod

### ISSUE THREAD

**Issue by koiboi-dev** [Cannoneers-of-Create/CreateBigCannons#658]
Use a handheld ram rod when attempting to load a cannon causes the below crashes

Was loading an AP shell and Big Cartridge into the cannon, after reloading the world the AP shell is loaded into the cannon.

[crash-2024-09-11_10.25.07-server.txt](https://github.com/user-attachments/files/16958803/crash-2024-09-11_10.25.07-server.txt)
[crash-2024-09-11_10.23.03-server.txt](https://github.com/user-attachments/files/16958802/crash-2024-09-11_10.23.03-server.txt)

<details>
<summary>Modlist</summary>

[Create Goggles (Create Plus) (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-goggles)
[Exposure (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/exposure)
[Etched (by jackson)](https://www.curseforge.com/minecraft/mc-mods/etched)
[Create: Connected (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/create-connected)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Create: ComputerCraft (CC: Tweaked) (by End_Rage)](https://www.curseforge.com/minecraft/texture-packs/create-computercraft)
[Leaky - Item Lag Fix[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/leaky)
[Petrolpark Library (by Petrolpark)](https://www.curseforge.com/minecraft/mc-mods/petrolpark-library)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[XL Packets (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[Create Big Cannons (by rbasamoyai)](https://www.curseforge.com/minecraft/mc-mods/create-big-cannons)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Amendments (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/amendments)
[CreateTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/createtweaker)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Create Compressed (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compressed)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[GoProne (by Alpvax)](https://www.curseforge.com/minecraft/mc-mods/goprone)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Create: Design n' Decor (by MilkyFur)](https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor)
[Krypton Reforged (by Txni)](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Ping Wheel (by LukenSkyne)](https://www.curseforge.com/minecraft/mc-mods/ping-wheel)
[Fast IP Ping (by Fallen_Breath)](https://www.curseforge.com/minecraft/mc-mods/fast-ip-ping)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[UltimaCraft PBR (by GrandMagus)](https://www.curseforge.com/minecraft/texture-packs/ultimacraft-pbr)
[Clockwork: Create x Valkyrien Skies (by rubydesic)](https://www.curseforge.com/minecraft/mc-mods/create-clockwork)
[Just Zoom (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/just-zoom)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Rechiseled: Create (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled-create)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Packet Fixer (by TonimatasDEV)](https://www.curseforge.com/minecraft/mc-mods/packet-fixer)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Measurements (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/measurements)
[Create: The Factory Must Grow (by Dr_Mango_Tea)](https://www.curseforge.com/minecraft/mc-mods/create-industry)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Origin Realms - Emissive (by Nebby_56)](https://www.curseforge.com/minecraft/texture-packs/origin-realms-emissive)
[World Border (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/world-border)
[Better Ping Display (by Quintinity)](https://www.curseforge.com/minecraft/mc-mods/better-ping-display)
[rbasamoyai's Betsy Ross (by rbasamoyai)](https://www.curseforge.com/minecraft/mc-mods/rbasamoyais-betsy-ross)
[Create: Bells & Whistles (by syslev)](https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Bullet Fix (by IAteMinecraf)](https://www.curseforge.com/minecraft/mc-mods/bullet-fix)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Create: Bitterballen (by pyzpre)](https://www.curseforge.com/minecraft/mc-mods/create-bitterballen)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Create: New Age (by nullBlade)](https://www.curseforge.com/minecraft/mc-mods/create-new-age)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Create: Pattern Schematics (by CakeIsTastyDeveloper)](https://www.curseforge.com/minecraft/mc-mods/create-pattern-schematics)
[Petrol's Parts (Create add-on) (by Petrolpark)](https://www.curseforge.com/minecraft/mc-mods/petrols-parts)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Create Railways Navigator (by MrJulsen)](https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Eureka! Ships! for Valkyrien Skies (Forge/Fabric) (by rubydesic)](https://www.curseforge.com/minecraft/mc-mods/eureka-ships)
[Lychee (Forge) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/lychee)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Create: Broken Bad (by jetpacker06)](https://www.curseforge.com/minecraft/mc-mods/create-broken-bad)
[Create: Factory (by antopfr90)](https://www.curseforge.com/minecraft/mc-mods/create-factory)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Create Mechanical Spawner (by oierbravo_mc)](https://www.curseforge.com/minecraft/mc-mods/create-mechanical-spawner)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[CC: Tweaked (by SquidDev)](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Create Cafe (by Myst)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[BSL Shaders - Original (by capttatsu)](https://www.curseforge.com/minecraft/shaders/bsl-shaders)
[Konkrete [Forge/NeoForge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Farsight [Forge/Neo] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Create: Numismatics (by IThundxr)](https://www.curseforge.com/minecraft/mc-mods/numismatics)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Create Cobblestone (by MR_sticky_piston)](https://www.curseforge.com/minecraft/mc-mods/create-cobblestone)
[Create: TaCZ Automation (by TerraPixel)](https://www.curseforge.com/minecraft/mc-mods/create-tacz-automation)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[MoreJS (by Lytho)](https://www.curseforge.com/minecraft/mc-mods/morejs)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Create: Modern Train Parts (by dugske)](https://www.curseforge.com/minecraft/mc-mods/create-modern-train-parts)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[Create Tank Defenses (by ItsRuby05)](https://www.curseforge.com/minecraft/mc-mods/create-tank-defenses)
[Radium Reforged (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Crash Utilities (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/crash-utilities)
[Create: Netherless (Forge) (by DariusZeBaguette)](https://www.curseforge.com/minecraft/mc-mods/create-netherless)
[DEUF - Duplicate Entity UUID Fix (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Lexiconfig (by CodinGlitch)](https://www.curseforge.com/minecraft/mc-mods/lexiconfig)
[Embeddium (Rubidium) Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Create: Ultimate Factory [Forge/Fabric] (by robinfrt)](https://www.curseforge.com/minecraft/mc-mods/create-ultimate-factory)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Create: Molten Metals (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/create-molten-metals)
[Create: Copycats+ (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/copycats)
[Please Not Another Vanilla PBR (by LackinToesTwitch)](https://www.curseforge.com/minecraft/texture-packs/please-not-another-vanilla-pbr)
[Create Central Kitchen (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
[Create Ratatouille (by Neve3)](https://www.curseforge.com/minecraft/mc-mods/create-ratatouille)
[[TaCZ] Timeless and Classics Zero (by nekocrane)](https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero)
[Create: Ender Transmission (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-ender-transmission)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Create: Addon Compatibility (by Amronos)](https://www.curseforge.com/minecraft/mc-mods/createaddoncompatibility)
[MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
[Fast Async World Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric)
[Carbon Config (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/carbon-config)
[Valkyrien Skies (Forge/Fabric) (by triode_)](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies)
[Create: Interiors (by syslev)](https://www.curseforge.com/minecraft/mc-mods/interiors)
[Trackwork (by Endal)](https://www.curseforge.com/minecraft/mc-mods/trackwork)
[Create: Eureka! (by FixerSchis)](https://www.curseforge.com/minecraft/mc-mods/create-eureka)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[Eureka! Create Airships! (by End_Rage)](https://www.curseforge.com/minecraft/texture-packs/eureka-create-airships)
[CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[TACZ: Durability (Timeless and Classics Guns) (by jeducklet)](https://www.curseforge.com/minecraft/mc-mods/tacz-durability)
[Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[BadOptimizations (by thosea)](https://www.curseforge.com/minecraft/mc-mods/badoptimizations)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Embrace Pixels - 16x Default PBR (by Mwteusz)](https://www.curseforge.com/minecraft/texture-packs/embrace-pixels)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Create : Misc & Things (by To0pa)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Create: Dreams & Desires (by Luna)](https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires)
[Simple Voice Radio (by CodinGlitch)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-radio)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Redirector [Modern] (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/redirector)
[Memory Settings[Neo/Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[Create: Tweaked Controllers (by getItemFromBlock)](https://www.curseforge.com/minecraft/mc-mods/create-tweaked-controllers)
[Chunk-Pregenerator (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Rechiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Create: Steam 'n' Rails (by IThundxr)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)

</details>

**Comment by rbasamoyai** [comment]
Create Big Cannons 5.5.1 currently does not fully support Create 0.5.1.h. There will be an update in the near future (5.6.0).

**Comment by rbasamoyai** [comment]
Fixed recently, not in release yet
