### ISSUE TITLE
Allow for train mounted artillery

### ISSUE THREAD

**Issue by YackMyGack** [Cannoneers-of-Create/CreateBigCannons#659]
It would be very nice if we could put these guns on trains.

Maybe there could be a train specific gun mount that has a seat to allow a passenger to control the gun?

**Comment by rbasamoyai** [comment]
It would not be that far of a stretch to make cannon subcontraptions on trains work.

However, the dealbreaker is that loading mechanisms (aside from possibly a manually operated quickfiring breech) would not work at all.

In addition, most redstone does not work easily either, which the Cannon Mount depends on, so this idea is unfortunately infeasible without large change to Create's contraption code.

None can do.

**Comment by YackMyGack** [comment]
perhaps instead of using redstone and other things for loading mechanisms it could use the train's inventory? moving the cannon could be similar to how the mountable cannons work.

**Comment by rbasamoyai** [comment]
Redstone is still needed for the firing mechanism.
