### ISSUE TITLE
Create Big Cannons pre-assembled cannon cannot be mounted on Eureka ship

### ISSUE THREAD

**Issue by Daniel366Cobra** [Cannoneers-of-Create/CreateBigCannons#667]
- Attempting to assemble the ship with mounted pre-assembled cannons via Eureka helm leads to cannons detaching from their mounts and remaining in block form.
- Attempting to move the cannon onto the mount of assembled ship and attach it by activating the mount does not work.
- Only hand-building the cannon on the mount of already assembled ship works, but in survival building cannons from parts needs silk touch and welding and only works with bronze or cast iron cannons.

Game version: 1.20.1

Mod versions:
Valkyrien Skies 2.3.0-beta.5
Eureka 1.5.1-beta.3
Create Eureka 1.0.0
Create Big Cannons 5.5.1

**Comment by rbasamoyai** [comment]
VS issue.
