### ISSUE TITLE
something isn't right with contraption system

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#67]
Itried to copy and paste contraption with cannons and this happened
![2022-08-06_20 07 46](https://user-images.githubusercontent.com/109973204/183260891-40a420b3-4deb-4576-ab31-fd0849cdbebb.png)
left is original cannon, right is "ghost" with collision, but i can't break it
i dk how to reproduse it, but i can give you schematics with this bug

**Comment by rbasamoyai** [comment]
Try `/flywheel backend` and switch the setting back and forth to "refresh" the rendering engine. If it isn't graphical (which you seem to suggest that it isn't), I'll take a look at it

**Comment by Crabanutij** [comment]
https://drive.google.com/file/d/1W93zdXxSAoLJk8i7xP3W5M0suAzHMmgs/view?usp=sharing 
it works in different worlds though, maybe problem in this schematics?
Edited: Those "cannon entities" still in schematics, even if i deleted cannon mountings and cannons.
![2022-08-07_12 40 02](https://user-images.githubusercontent.com/109973204/183287022-2a20ee80-08d9-4e8d-8030-960b2dd46fd9.png)
