### ISSUE TITLE
Incompatibilty with eureka/VS2 and autocannons turret

### ISSUE THREAD

**Issue by Trabyzonde** [Cannoneers-of-Create/CreateBigCannons#671]
When using a wrench to change the end of an autocannon on an assemble ship and you mount the autocannon to use it as a turret, the camera get stuck in the cannon (the piece of the cannon above the cannon mount to be exact) and it is impossible to aim properly.
Even using f5 to use the third person view it is annoying at the best and all the cannon parts seems to be merged into one. And also, no sound is emited wehn using the autocannon.
I tried the Create interactive mod but it didn't change anything. 
It is not specially a critical bug but it is quite annoying

**Comment by rbasamoyai** [comment]
Eureka/VS2 issue, won't fix
