### ISSUE TITLE
[1.20.1] Basic attributes of configurable cannons

### ISSUE THREAD

**Issue by HaktyGaona** [Cannoneers-of-Create/CreateBigCannons#673]
I hope to add more configuration options for cannons, such as the firing speed of autocannon shells, the damage multiplier of shells, the customizable firing rate of the autocannon, more ways to load cannon mount so on.
(I know it's possible to adjust the multiplier with datapacks, but I don't know how to solve the problem of shell ejection speed. I feel that the flight speed of autocannon shells is too slow. A folder called `exemplar_createbigCannons` seems to have relevant content, but I don't know how it works.)

**Comment by rbasamoyai** [comment]
Most attributes in Create Big Cannons are changed using data packs.

**Comment by HaktyGaona** [comment]
I found the way to use it, it's working now
