### ISSUE TITLE
Projectiles can not harm eureka ships

### ISSUE THREAD

**Issue by WorldsOfRosefire** [Cannoneers-of-Create/CreateBigCannons#688]
I am sorry but the cannons can not harm Eureka ships. I am currently shooting from a unassambled ship (means normal build) at a Eureka structure. take a look:
https://cdn.discordapp.com/attachments/1089167214495666206/1297702371593420842/Undestroyable.mp4?ex=6716e303&is=67159183&hm=0d4f5608d6b01663108ad4bcd39f7b0c70d98940a444f318a7db18c0e705c19b&
as you see the other projectile can do damage.
would love if this could work. eureka+create+bigcannons=huge potential.
Minecraft 1.20.1
Forge 47.3.11
createbigcannons-5.6.0-mc.1.20.1-forge
create-1.20.1-0.5.1.i
eureka-1201-1.5.1-beta.3
valkyrienskies-120-2.3.0-beta.5

**Comment by rbasamoyai** [comment]
VS compat issue, not responsible
