### ISSUE TITLE
Game crash when shooting "glass fluid pipe"

### ISSUE THREAD

**Issue by jay-ari** [Cannoneers-of-Create/CreateBigCannons#689]
I believe this goes here, but if I am mistaken please let me know.
My friend was shooting at a contraption, using light rounds with the cannon, when suddenly both of our games crashed.
We have experimented further and found every time we broke the glass section of a pipe with the cannon it caused a crash.
We are on the latest build for 1.19.2.
I have attached the error message below. I hope this helps.
![image](https://github.com/user-attachments/assets/3ea1f396-cba3-4b27-82c4-c20fb76466cb)

**Comment by rbasamoyai** [comment]
Could you provide the crash report?

**Comment by rbasamoyai** [comment]
Bump

**Comment by rbasamoyai** [comment]
Closing since can't reproduce without evidence.
