### ISSUE TITLE
Hi, how can I change the power of the projectile

### ISSUE THREAD

**Issue by tilonin** [Cannoneers-of-Create/CreateBigCannons#690]
How or where can I change the projectile power in your code?

**Comment by rbasamoyai** [comment]
See the data pack system in https://github.com/Cannoneers-of-Create/CreateBigCannons/tree/1.18.2%2Fdev/common%2Fsrc%2Fmain%2Fresources%2Fdata%2Fcreatebigcannons%2Fmunition_properties.

Projectile balancing contributions are generally not accepted.
