### ISSUE TITLE
Crashing when using HEAT shell

### ISSUE THREAD

**Issue by gageb438** [Cannoneers-of-Create/CreateBigCannons#691]
I put the HEAT shell into a big cannon, fire it, game instantly crashes.

**Comment by rbasamoyai** [comment]
Send a crash report.

**Comment by gageb438** [comment]
Will send it when I get home. Busy at the moment.

**Comment by rbasamoyai** [comment]
Bump

**Comment by gageb438** [comment]
Sorry, entirely forgot about this, found out my issue was with another mod not this one, sorry for wasting your time.
