### ISSUE TITLE
Flak Autocannon Round Dupe

### ISSUE THREAD

**Issue by Legomountain14** [Cannoneers-of-Create/CreateBigCannons#692]
I found this dupe a few days ago while playing a survival server. It works in both singleplayer and multiplayer. Here is a [video](https://youtu.be/_ZK5NQw94xs) of the process. 

Here is my modlist:

- Create -- 0.5.1-f-build.1417+mc1.20.1
- Create Big Cannons -- 5.5.1+mc.1.20.1-fabric
- Fabric API -- 0.92.2+1.20.1
- Indium -- 1.0.34+mc1.20.1
- Lithium -- mc1.20.1-0.11.2
- Reese's Sodium Options -- 1.7.2+mc1.20.1-build.101
- Sodium -- 0.5.11+mc1.20.1
- Sodium Extra -- 0.5.4+mc1.20.1-build.115

Fabric version 0.16.9

**Comment by rbasamoyai** [comment]
Fixed in #698
