### ISSUE TITLE
Crashing when using cannons

### ISSUE THREAD

**Issue by R1kich** [Cannoneers-of-Create/CreateBigCannons#693]
When I put the breech or gun mount, the game immediately crashes with exit code -1

Here is the list of mods
![изображение](https://github.com/user-attachments/assets/c9e03f0f-f15b-4b86-b3ac-cd9d101c831e)

[crash-2024-11-10_14.05.16-client.txt](https://github.com/user-attachments/files/17691167/crash-2024-11-10_14.05.16-client.txt)

**Comment by rbasamoyai** [comment]
https://images-ext-1.discordapp.net/external/UietTu8Eg8AtA60CbkeheEAx5Yqy3Ol380042bjz4PU/https/host.ithundxr.dev/RgHUwh.png

Try these versions of Sodium, Indium, and Fabric API.
