### ISSUE TITLE
Big Cannons and Immersive Portals/Carpet compatiblity issue

### ISSUE THREAD

**Issue by DurekuRyuu** [Cannoneers-of-Create/CreateBigCannons#694]
Alrighty, so I think I've found an incompatibility between Big Cannons and 2 other mods, causing a crash on world load.

- Immersive Portals
- Carpet

All three mods seem to do something with Lnet/minecraft/class_3222, and my gut says immersive portals is the primary conflict due to it just not playing well with other mods.

I've been driving myself up the wall browsing the open and closed issues to find something to do with class_3222 or other keywords to find similar issues in hopes of finding a solution. No dice.

This modpack is definitely a mess, with semi-conflicting mods used together because I'm stubborn and to have my cake and eat it twice more after.

Let me know if I'm barking up the wrong tree, thank.
[latest.log](https://github.com/user-attachments/files/17708292/latest.log)
[crash-2024-11-11_14.05.15-server.txt](https://github.com/user-attachments/files/17708293/crash-2024-11-11_14.05.15-server.txt)

**Comment by rbasamoyai** [comment]
Will investigate, unsure if this can be fixed on Create Big Cannons' end, since Immersive Portals generally seems pervasive

**Comment by rbasamoyai** [comment]
But yes, this is seemingly a conflict with Immersive Portals
