### ISSUE TITLE
After the Create update, I am unable to access the archive

### ISSUE THREAD

**Issue by whydm2003724** [Cannoneers-of-Create/CreateBigCannons#696]
I am version 1.20.1 of Fabric, and the mod version is (creat-fabric-0.5.1-j-build.1604+mc1.20.1). This mod is the latest version, and this is an error report;[crash-2024-12-02_19.02.51-client.txt](https://github.com/user-attachments/files/17977107/crash-2024-12-02_19.02.51-client.txt)

**Comment by RubyCascade** [comment]
I also encountered the same issue

**Comment by rbasamoyai** [comment]
This is because Create Big Cannons does not yet support that version. It will be updated in the future.
