### ISSUE TITLE
Doesn't register Flywheel 1.18-0.6.5 being being "1.18-0.6.3 or above"

### ISSUE THREAD

**Issue by Corvus20** [Cannoneers-of-Create/CreateBigCannons#70]
**Describe the issue**
Despite Flywheel 1.18-0.6.5 being above 1.18-0.6.3, Big Cannons does not register it as such and refuses to launch.

 - OS: Windows
 - CreateBigCannons Version: beta-0.3
 - Other Mods: My main modlist is MASSIVE. but being that this is a basic dependency problem, I imagine it would behave the same in an instance with just the required mods.

**To Reproduce**
1. Install beta-0.3 of Create Big Cannons, Flywheel 1.18-0.6.5, and Create 1.18.2-0.5.0d
2. Launch game
3. Wait for game to load into the loading error screen

**Expected behavior**
Create Big Cannons should see that Flywheel 1.18-0.6.5 is in fact above the version 1.18-0.6.3

**Screenshots**
![image](https://user-images.githubusercontent.com/75586106/184683056-85dfee48-02d5-4f26-8837-ddaf3f928f22.png)

**Comment by rbasamoyai** [comment]
0.5d compatibility will be worked on, please use 0.5c and Flywheel 0.6.3 for now
