### ISSUE TITLE
When joining a world, It crashes Minecraft before entering.

### ISSUE THREAD

**Issue by MedeivelMcRPG** [Cannoneers-of-Create/CreateBigCannons#705]
When I open Minecraft everything seems to work properly but when I join a world, it say's joining world than saving world and after saving world, it completely crashes Minecraft. After that it gives a crash message that says (The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_5854()" because "player" is null)

**Comment by rbasamoyai** [comment]
Send the crash report. Seems like an issue with CBC not being updated to support Create 0.5.1.j yet though

**Comment by rbasamoyai** [comment]
Closing since no crash report
