### ISSUE TITLE
BigCannons breaks Rope Pulley Synchronization

### ISSUE THREAD

**Issue by Zygal-cvg** [Cannoneers-of-Create/CreateBigCannons#706]
Rope Pulley registers the pulley magnet of another synchronized Rope Pulley as an unmoveable object, this causes a placed Rope Pulley contraption to not be able re-assemble when pulled back up.

This happens in the latest Forge versions of Create and Create: Big Cannons for 1.18.2 and 1.20.1 with no other mods on

![2024-12-10_20 07 49](https://github.com/user-attachments/assets/428ca4f1-40a0-4312-af76-a0bc3f4e3c5b)

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/707
