### ISSUE TITLE
flywheel doesn t work

### ISSUE THREAD

**Issue by megan1234sda** [Cannoneers-of-Create/CreateBigCannons#71]
**Describe the issue**
A clear and concise description of what the issue is.

 - OS: [e.g. Windows]
 - CreateBigCannons Version: [e.g. nightly-4b2bde7 / beta-0.1]
 - Other Mods: [e.g. Waystones 1.18.2-10.1.0]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by rbasamoyai** [comment]
Not enough info, as well if it has to do with Flywheel 0.6.5 and Create 0.5.0d not working with the mod it's because it hasn't been updated yet, but it will in `beta-0.4`
