### ISSUE TITLE
Incorrect location of the AP projectile and failure of the fuses

### ISSUE THREAD

**Issue by Ford3l** [Cannoneers-of-Create/CreateBigCannons#711]
Sorry for a bad video, GitHub prohibits uploading files larger than 10 Mb

https://github.com/user-attachments/assets/0b85fbf6-348c-46f8-9806-03302e06fc5e

**Comment by rbasamoyai** [comment]
Can you provide a summary of what you believe is broken?

**Comment by rbasamoyai** [comment]
Looked at the video again, everything working as intended. Fuze mechanics could probably be explained better, but basically shells fuzed at the base (i.e. AP shell) do not activate impact or proximity fuzes.
