### ISSUE TITLE
A bug on the server side when loading shells

### ISSUE THREAD

**Issue by Ford3l** [Cannoneers-of-Create/CreateBigCannons#718]
I noticed an error that caused the projectiles to load incorrectly into the barrel on the server, but at the same time everything is fine in the single-player game - watch the video: https://youtu.be/zAD56veKtd8?si=uAXzvJfzLQtxygoZ
If you need any additional information, please write

**Comment by rbasamoyai** [comment]
Could you provide a modlist, highlighting the Create Big Cannons version and the Create version, as well as other mods?

**Comment by Ford3l** [comment]
> Could you provide a modlist, highlighting the Create Big Cannons version and the Create version, as well as other mods?

here you are - 

1. ad_astra-fabric-1.20.1-1.15.jar
2. AmbientSounds_FABRIC_v6.4.1_mc1.20.1.jar
3. BadOptimizations-2.2.1-1.20.1.jar
4. bellsandwhistles-0.4.5+1.20.1-FA-BRIC.jar
5. Better Cave Dweller-1.2.0-fabric.jar
6. betterbiomeblend-1.2-fabric.jar
7. BetterPingDisplay-Fabric-1.20.1.jar
8. BiomesOPlenty-fabric-1.20.1-19.0.1.94.jar
9. botarium-fabric-1.20.1-2.3.4.jar
10. c2me-fabric-mc1.20.1-0.2.0-alpha.11.13.jar
11. chatanimat-1.0.5.jar
12. cloth-config-11.1.136-fabric.jar
13. continuity-3.0.0-1.1.jar
14. coroutil-fabric-1.20.1-1.3.jar
15. createbigcannons-5.1-fabric.jar
16. create-fabric-0.5.1-b-ud.1631-mc1.20.1.jar
17. create-new-compresed-steel-1.3.jar
18. CreativeCore_FABRIC_v2.12.24_mc1.20.1.jar
19. creeperoverhaul-3.0.2-fabric.jar
20. Debugify-1.20.1-1.2.0.jar
21. DynamicSurroundings-Fabric-1.2.jar
22. elytraitems-fabric-3.5.6+1.20.1.jar
23. endermanoverhaul-fabric-1.20.1.jar
24. enhancedlockentities-0.9+1.20.1.jar
25. EnhancedVisuals_FABRIC_v1.8.1_mc1.20.1.jar
26. explosive-e-fabric-1.20.1.jar
27. exposure-1.20.1-1.7.7.jar
28. fabric-api-0.92.2+1.20.1.jar
29. fabric-language-kotlin-1.10.3+kot-lin.1.2.0.jar
30. ferritecore-6.0.1-fabric.jar
31. fzy_config-fabric-1.20.1.jar
32. geckolib-fabric-1.20.1-4.4.9.jar
33. GlitchCore-Fabric-1.20.1.jar
34. immersive_aircraft-1.15+1.20.1-fabric.jar
35. indium-1.0.34+mc1.20.1.jar
36. iris-1.7.5-mc1.20.1.jar
37. krypton-0.2.3.jar
38. lambdynalights-2.3.2+1.20.1.jar
39. lithium-fabric-mc1.20.1-0.11.2.jar
40. man_of_many_planes-0.2.0+1.20.1-fabric.jar
41. memoryleakfix-fabric-1.17+.1.15.jar
42. modmenu-7.2.2.jar
43. MRU-1.0.4-fabric.jar
44. naturalist-fabric-0.4.3+1.20.1.jar
45. netherweather-1.1.2_b.jar
46. noisium-fabric-1.20.1-1.0.1.jar
47. owo-lib-0.11.2+1.20.jar
48. particle_core-0.2.5+1.20.jar
49. particular-1.1.1.jar
50. PresenceFootsteps-1.20.1-0.14.1.jar
51. resourceful-config-fabric-1.20.1-1.2.jar
52. resourceful-lib-fabric-1.20.1-2.1.29.jar
53. sleepwarp-fabric-1.20.1.jar
54. smokesignals-1.0+1.20.1.jar
55. sodium-extra-0.5.4+mc1.20.1-build.d115.jar
56. sodium-fabric-0.5.11+mc1.20.1-build.115.jar
57. sodium-shadowy-path-blocks-3.4.jar
58. sound-physics-remastered-fabric-1.20.1-1.20.jar
59. Sounds-2.2-1+1.20.1-fabric.jar
60. starlight-1.2+fabric.dbc156f.jar
61. Steam_Rail-FABRIC-5.1.9-fab-mc1.20.1.jar
62. SubtleEffects-fabric-0.5.1-1.20.1.jar
63. sushi_bar-0.2.2+1.20.jar
64. tacz-fabric-1.20.1-0.1-hotfix3.jar
65. TerraBlender-fabric-1.20.1-3.3.0.174.jar
66. TreeChopper-1.20.1-0.19.0.jar
67. visuality-0.7.14-1.20.jar
68. zombiewareness-fabric-1.20.1-1.13.1.jar

**Comment by rbasamoyai** [comment]
The Create Big Cannons file looks odd, could you send the precise version?

**Comment by rbasamoyai** [comment]
Also, can you send the server mod list?

**Comment by rbasamoyai** [comment]
Bump

**Comment by rbasamoyai** [comment]
Managed to replicate this, fixed in-dev
