### ISSUE TITLE
bug with base create Mechanical Drills & Rope Pulleys

### ISSUE THREAD

**Issue by AlchemicalDerp** [Cannoneers-of-Create/CreateBigCannons#719]
Using:
Forge version 47.3.12 (I've seen the exact issue be reported to the Create team using version 47.3.6 with Create big cannons installed)

create-1.20.1-0.5.1.j
createbigcannons-5.7.2-mc.1.20.1-forge

When Create Big Cannons is installed, for a seemingly unexplainable reason, rope pulleys do not work properly with Mechanical Drills. Causing the drill to in a sense, become stuck in bedrock/immovable blocks. 

I've attached the following video as a demonstration.
https://youtu.be/bSEviWOA334

**Comment by rbasamoyai** [comment]
I believe this to be fixed in-dev. Try the latest nightly build available on the Discord server.

**Comment by AlchemicalDerp** [comment]
[crash-2024-12-29_21.57.01-fml.txt](https://github.com/user-attachments/files/18271731/crash-2024-12-29_21.57.01-fml.txt)
It was suggested I try the latest build, build 139. I was unable to load into the instance. And build 138 doesn't yet have the patch.
