### ISSUE TITLE
something doesn't work when using with another mod

### ISSUE THREAD

**Issue by HoodBlah** [Cannoneers-of-Create/CreateBigCannons#72]
**Describe the issue**
Big cannon doesnt work with latest flywheel

 - OS: [e.g. Windows]
 - CreateBigCannons Version: [createbigcannons-1.18.2-beta-0.3]
 - Other Mods: [flywheel 0.6.5]

**To Reproduce**
1. install latest flywheel
2. install latest big cannon from curseforge
3. startup minecraft

**Expected behavior**
For it to load together

**Screenshots**
![image](https://user-images.githubusercontent.com/89415523/185506659-70a26803-77f3-4f6a-8335-407240a672d9.png)

**Comment by Crabanutij** [comment]
Will fix in the next beta version

**Comment by rbasamoyai** [comment]
Should be fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/dffe8285a448eb5a94fb718853fdc1c855aac4d4.
