### ISSUE TITLE
Mod Crashes with Create 0.5d/ Flywheel 6.5

### ISSUE THREAD

**Issue by Hahahavana** [Cannoneers-of-Create/CreateBigCannons#73]
As stated in the title, mod crashes during startup if used with the newest version of create.

**To Reproduce**
1. Install Newest version of Create and Flywheel
2.There is no step 2

**Comment by rbasamoyai** [comment]
Fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/dffe8285a448eb5a94fb718853fdc1c855aac4d4. Not a release build yet.
