### ISSUE TITLE
Fixed Cannon Mount and Wired Fuze missing crafting recipes

### ISSUE THREAD

**Issue by SageofTurtles** [Cannoneers-of-Create/CreateBigCannons#730]
Hello!  I just updated this mod to the latest version (5.8.0) for Forge on 1.20.1.  This version added Fixed Cannon Mounts and Wired Fuzes, but I am unable to find any recipes to craft these new items.  I've checked both the mod's JAR files and in-game using JEI, but there doesn't appear to be any way to make these new items.  I'm wondering if perhaps the recipes were not included in the release for some reason?

**Comment by rbasamoyai** [comment]
There are some things I overlook, and this is one of them

yay

**Comment by rbasamoyai** [comment]
Fixed in-dev, will be found in 5.8.1
