### ISSUE TITLE
Server crashing problem caused of HE shells

### ISSUE THREAD

**Issue by fekenkenny** [Cannoneers-of-Create/CreateBigCannons#731]
In multigames , the server will crash right after the fired HE shell reached the block.
The Neruina reported that the problem happened on the mixin.

Mod version 5.6.0-dev-mc.1.20.1-forge-build.87
Minecraft version 1.20.1 Forge 47.3.10

Here is the Crash Report
[crash_report.txt](https://github.com/user-attachments/files/18282197/crash_report.txt)

The Information from Neruina

![image](https://github.com/user-attachments/assets/6c549d03-324e-406b-9b7a-0bd937dcf240)

The Mod List
![0e201a6d715f616d673367af126f246](https://github.com/user-attachments/assets/6e1391e6-c6f0-4edd-bcd7-ce38799e858c)

**Comment by rbasamoyai** [comment]
Update to Create Big Cannons 5.8.0. Also, can you try reproducing this issue with just Create and Create Big Cannons?

**Comment by fekenkenny** [comment]
Using 5.6.0 version is for the compatibility with the Valkyr and I will try it now.

**Comment by fekenkenny** [comment]
Cant reproducing this issue with only Create and Create Big Cannons.
Located the problem is incompatiable with VS Addtion after tests,I will delete it.Thanks for you help!
