### ISSUE TITLE
you cant lauch it with the newest version of Flywheel

### ISSUE THREAD

**Issue by Redstonesimi** [Cannoneers-of-Create/CreateBigCannons#76]
you cant lauch it with the newest version of Flywheel

**Comment by rbasamoyai** [comment]
Already fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/dffe8285a448eb5a94fb718853fdc1c855aac4d4. Please download the latest nightly if you want to play with Create 0.5.0d and Flywheel 0.6.5, or downgrade to Create 0.5.0c and Flywheel 1.18.2-0.6.3.

**Comment by Redstonesimi** [comment]
ok thx
