### ISSUE TITLE
[1.18.2] Requires flywheel 1.18-0.6.3 or above but I use Flywheel 0.6.5

### ISSUE THREAD

**Issue by BelgianDev** [Cannoneers-of-Create/CreateBigCannons#78]
**Describe the bug**
The game crashes saying  requires flywheel 1.18-0.6.3 or above but I use Flywheel  0.6.5

 - OS: Windows 11 and Debian 11 (Linux)
 - Version: 1.18.2-beta-0.3

**To Reproduce**
1. Install Create and Flywheel
3. Then install Create Big Cannons
4. Start your game
5. See crash

**Expected behavior**
That the game starts

**Screenshots**
[latest.log](https://github.com/rbasamoyai/CreateBigCannons/files/9432855/latest.log)

**Comment by rbasamoyai** [comment]
Already acknowledged in https://github.com/rbasamoyai/CreateBigCannons/issues/76
