### ISSUE TITLE
[bug] flywheel crash

### ISSUE THREAD

**Issue by soggyfever4568** [Cannoneers-of-Create/CreateBigCannons#79]
I know this is a much stated issue by others at this point but despite having everything updated as Ive seen stated, im still getting the Mod createbigcannons requires flywheel 1.18-0.6.3 or above crash. here's the crash report:
[crash-2022-08-29_09.09.15-fml.txt](https://github.com/rbasamoyai/CreateBigCannons/files/9446222/crash-2022-08-29_09.09.15-fml.txt)

**Comment by rbasamoyai** [comment]
Already acknowledged in https://github.com/rbasamoyai/CreateBigCannons/issues/76
