### ISSUE TITLE
Projectiles get stuck in the ground and doesn't detonate

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#8]
the impact fuse he shells just gets stuck into the ground after penetration and only explodes when all of the blocks around it are deleted so it starts falling again and hits something else
![obraz](https://user-images.githubusercontent.com/71346253/180566426-6d3e110b-06ee-42c6-b80f-53e8142f1ecd.png)
image of the he shell with impact fuse falling after deleting the dirt cube it was stuck in (falls and then finally explodes)
it gets stuck on other blocks too
![obraz](https://user-images.githubusercontent.com/71346253/180566806-69a91a8e-a51c-4d86-a579-d2298a2bc52e.png)
![obraz](https://user-images.githubusercontent.com/71346253/180566832-cdb84200-8e7c-4539-b47f-f17157de1be8.png)
![obraz](https://user-images.githubusercontent.com/71346253/180566877-fbdee338-4a9a-426e-9421-d2bc094ce6a2.png)
nvm now it fell to the ground

**Comment by Abrams11IsBack** [comment]
![obraz](https://user-images.githubusercontent.com/71346253/180567524-80ad6a8e-e609-4baa-ac58-9274664d538b.png)

note, it seems to only happen when the target is close to the cannon, on larger distances it works perfectly fine

**Comment by Abrams11IsBack** [comment]
![obraz](https://user-images.githubusercontent.com/71346253/180569868-cd65d90d-81a0-4426-bd2b-34e3822f2e06.png)
the same thing happens when the projectile is not rendered / if the render distance/simulation distance if not covering the whole trajectory the projectile gets stuck

**Comment by Abrams11IsBack** [comment]
![obraz](https://user-images.githubusercontent.com/71346253/180574603-26064dfe-1c12-4bc9-91d4-c88c23004941.png)
so the velocity seems to be the problem, a projectile went through my tank and exploded after some time without leaving penetration damage

**Comment by rbasamoyai** [comment]
Bit late but I did clarify to you in the discord that impact fuzes might have a chance of detonating or not, for now I'll close this but I'd like it if someone tried it out with 100% detonation rate when config comes out 👍
