### ISSUE TITLE
Incompatibility with new versions of Create & Flywheel

### ISSUE THREAD

**Issue by WOSAJ** [Cannoneers-of-Create/CreateBigCannons#80]
**Describe the bug**
The mod refuses to load on Flywheel versions higher than 0.6.3 if you change mods.html , then I get NoSuchMethodError, apparently in some update Create mod removed these classes

 - OS: Windows
 - Version: beta-0.3
 - Create 0.5.0.d
 - Flywheel 0.6.5

**To Reproduce**
Just launch Minecraft

**Expected behavior**
Minecraft starts?!

**Screenshots**
![image](https://user-images.githubusercontent.com/76728834/187827564-81806a47-0b7d-4224-8365-5658902289d6.png)

**Comment by rbasamoyai** [comment]
Already acknowledged in #76
