### ISSUE TITLE
doesn't recognize a newer version of flywheel

### ISSUE THREAD

**Issue by darkblood159** [Cannoneers-of-Create/CreateBigCannons#86]
**Doesn't recognize a newer version of flywheel**
A clear and concise description of what the issue is.

 - OS: [e.g. Windows]
 - CreateBigCannons Version: [beta 0.3]
 - Other Mods: [e.g. FlyWheel 1.18.2-0.6.5]

**To Reproduce**
download and install flywheel 1.18.2-0.6.5
download and install CreateBigCannons beta 0.3
receive error.

**Expected behavior**
for it to work properly with the updated flywheel

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/53360355/189773840-8ed0c25b-1a47-4f84-9bd1-3dc58b092860.png)

**Comment by rbasamoyai** [comment]
See https://github.com/rbasamoyai/CreateBigCannons/issues/76
