### ISSUE TITLE
basin foundry lid render bug

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#88]
When place createbigcannons:basin_foundry_lid on solid block, this solid block doesn't render properly
![2022-09-20_11 26 37](https://user-images.githubusercontent.com/109973204/191222242-933c3878-47fb-497f-83f4-46578c639978.png)
One small question: What is the purpose of cannon layers? How do i use them?
P.S.
I used rubidium,
and how do i use cannon builder?

**Comment by rbasamoyai** [comment]
Fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/addf8c8c597142dbb1d98bb7bba2bdca3c2986a6
