### ISSUE TITLE
unbored very small cannon layer has the same texture as nethersteel cannon layer

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#89]
make it brighter pls ;)
p.s. steel is on the left, also i have noticed they have the same id, which is odd
![2022-09-20_17 31 30](https://user-images.githubusercontent.com/109973204/191301344-9154fe81-63a8-4426-81b0-87c7abece05f.png)

**Comment by rbasamoyai** [comment]
Fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/addf8c8c597142dbb1d98bb7bba2bdca3c2986a6
