### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Syphos-36** [Cannoneers-of-Create/CreateBigCannons#92]
I have the exact versions suggested on the curseforge page yet my game instantly crashes after launch with this file being generated. i think its saying i dont have flywheel but i have quite literally the exact version it states
[latest.log](https://github.com/rbasamoyai/CreateBigCannons/files/9658911/latest.log)

**Comment by rbasamoyai** [comment]
Issue sounds similar to #76, already fixed in nightlies. Log however is not a crash report and is uninformative.
